### ISSUE TITLE
Graph inputs vs value_info

### ISSUE THREAD

**Issue by postrational** [onnx/models#1]
I'm looking at some of the models gathered in this repository (SqueezeNet, DenseNet-121, ResNet-50) and I noticed a pattern.

All parameters of the graph are specified as `input` fields and none as `value_info` fields. This mixes model inputs and trainable parameters into a single set and I'm not sure how to distinguish between them.

Separating model inputs and trainable variables may be useful for frameworks, which distinguish the concepts of `placeholder` and `Variable`.

Would you agree or am I missing something?

**Comment by bddppq** [comment]
The Graph has a separated field `initializer` for storing all the parameters (both name and value), `input` is the type & shape information of the union of parameters and model input. We decided to go this way because if someday ONNX adds support for doing training, we can simply drop the `initializer` and still have the network structure well preserved. `value_info` is an optional field used for storing type & shape information of the inner-nodes in the graph.

**Comment by postrational** [comment]
Wouldn't it make sense to use `initializer` values also for parameters listed in `value_info` fields?

When importing the models as they stand today, would you suggest to treat all input fields as `Variable` type tensors? Or perhaps we should distinguish input `placeholders` by the fact that they don't have an associated `initializer`?

**Comment by bddppq** [comment]
I think they are different. `initializer` stores the values of the parameters, which are the external facing nodes, while in `value_info` it's just type and shape (of inner-nodes). `value_info` is mostly for tooling, type/shape inference for doing optimization.

They should be distinguished, (as you said) by checking whether its name appeared in the initializer.

**Comment by zakk0610** [comment]
Hi, 
I think this is potential bug for doing optimization. Because the `value_info` fields are none, user could not get the dimension of output value in the node on ONNX IR. (generated by graphProtoToGraph).

```
for (int j = 0; j < np.output_size(); j++) {
  auto out = n->outputs()[j];
  // we don't know the real type here, so that's done in a later pass
  out->setElemType(ONNX_NAMESPACE::TensorProto_DataType_UNDEFINED);
  out->setUniqueName(np.output(j));
  value_by_name_of[np.output(j)] = out;
}
```

```
for (int i = 0; i < gp.value_info_size(); i++) {
  value_by_name_of[gp.value_info(i).name()]->setElemType(gp.value_info(i).type().tensor_type().elem_type());
  value_by_name_of[gp.value_info(i).name()]->setSizes(tensorShapeProtoToDimensions(gp.value_info(i).type().tensor_type().shape()));
}
```

or this is my misunderstanding? 
Thanks

**Comment by vinitra** [comment]
This conversation was resolved in https://github.com/onnx/onnx/pull/1718.
