### ISSUE TITLE
Sample Code on README.md not working

### ISSUE THREAD

**Issue by rillomas** [onnx/models#10]
I tried running the sample code on README.md and got the following error.

```
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    import onnx_backend as backend
ImportError: No module named onnx_backend
```

I believe the sample is based on old code.

**Comment by BruceDai** [comment]
@rillomas , this code is just for example, you should firstly install Caffe2/Tensorflow as ONNX backend, also install onnx-caffe2/onnx-tensorflow, then you can use this code to replace the sample code
> import onnx_caffe2.backend as backend
or
> import onnx_tf .backend as backend

**Comment by rillomas** [comment]
@BruceDai It worked! Thank you!
