### ISSUE TITLE
Bug in inception_v1 model ?

### ISSUE THREAD

**Issue by LucasMahieu** [onnx/models#11]
Hi,

I have a question about the onnx model *inception_v1*.

The last AveragePool node have the following proto : 
> graph.node[-5]                                                                                                    
input: "inception_5b/output_1"
output: "pool5/7x7_s1_1"
name: ""
op_type: "AveragePool"
attribute {
  name: "strides"
  ints: 1
  ints: 1
  type: INTS
}
attribute {
  name: "pads"
  ints: 0
  ints: 0
  ints: 1
  ints: 1
  type: INTS
}
attribute {
  name: "kernel_shape"
  ints: 7
  ints: 7
  type: INTS
}

The input tensor shape is : [1, 1024, 7, 7]
So, an average pooling layer with kernel=7, stride=1, padding=0 before and 1 after will give an output tensor of shape [1, 1024, 2, 2].

This don't seem to make sense à the end of a network, where the output should be of shape [1, 1024, 1, 1].

So, according to me, the padding should be zero : 
attribute {
  name: "pads"
  ints: 0
  ints: 0
  ints: 0
  ints: 0
  type: INTS
}
As you can see here for example : http://ethereon.github.io/netscope/#/preset/googlenet

Does someone can tell me from were this model was generated ?

**Comment by vinitra** [comment]
Inception v1 was generated from Caffe2. Please see recent opsets which should resolve this issue.
