### ISSUE TITLE
Please post an ONNX LSTM model

### ISSUE THREAD

**Issue by mathisdon** [onnx/models#110]
I have found no ONNX models containing an LSTM operator anywhere on the internet.  Please post one,

**Comment by prasanthpul** [comment]
@guschmue I believe you have some

**Comment by guschmue** [comment]
let me think about something useful.

**Comment by WilliamTambellini** [comment]
+1 for a minimalist example onnx model with at least 1 rnn op (lstm or gru), whatever the task done by the NN.
I ve seen that discussion on pytorch forum : 
https://discuss.pytorch.org/t/request-for-minimal-example-of-exporting-recurrent-models-rnn-lstm-gru-to-onnx/21694

**Comment by mathisdon** [comment]
I believe that there are no valid ONNX files in existence that contain LSTM layers. I would love to see an ONNX file containing LSTMs that can be imported into onnx-tf. I believe there are none, Would someone like to prove me wrong? I would apreciate it. Thanks

**Comment by prasanthpul** [comment]
Internally we have a number of LSTM and GRU models converted from TF thanks to the https://github.com/onnx/tensorflow-onnx converter. Unfortunately most of them cannot be shared externally. @mx-iao is working to identify some that can be posted to the model zoo.

**Comment by guschmue** [comment]
how about a mnist using lstm ?

**Comment by WilliamTambellini** [comment]
The "docnn" example from pytext seems to embed a lstm cell :   
https://github.com/facebookresearch/pytext
but the onnx export (at least for that model) is currently a little buggy : 
https://github.com/facebookresearch/pytext/issues/248

**Comment by mathisdon** [comment]
No. It has now been theee months. I do not believe that the onnx lstm spec is workable. There are no examples of a transfer from one franework to a different franework. This is not a good sign for the future of onnx.

**Comment by WilliamTambellini** [comment]
microsoft onnxruntime has a LSTM example : 
onnxruntime/onnxruntime/test/testdata/CNTK/test_LSTM.tanh.bidirectional/model.onnx
https://github.com/Microsoft/onnxruntime/tree/master/onnxruntime/test/testdata/CNTK/test_LSTM.tanh.bidirectional

**Comment by WilliamTambellini** [comment]
Someone is trying to export the GNMT model to onnx : 
https://github.com/onnx/onnx/issues/1778
it s recurrent based embedding some LSTM cells.
WIP...

**Comment by guschmue** [comment]
hm, we could try to export gnmt via tensorflow model but I think this will use dynamic lstm which uses control flow and not the lstm op.

**Comment by WilliamTambellini** [comment]
[docnn-130.onnx.zip](https://github.com/onnx/models/files/2834757/docnn-130.onnx.zip)
as obtained by running the docnn example from pytext 
https://github.com/facebookresearch/pytext
and exporting to onnx via pytext/pytorch.
There is a LSTM cell but unclear yet if needing control flow...
tbc

**Comment by KeDengMS** [comment]
Added [BiDAF](https://github.com/onnx/models/pull/157) model, which has 5 layers of bidirectional LSTMs.
