### ISSUE TITLE
[Question] where do we upload the trained models?

### ISSUE THREAD

**Issue by bpinaya** [onnx/models#112]
Hi there, been using ONNX and wanted to contribute on the FCN section. I saw that in the [template here](https://github.com/onnx/models/tree/master/models/image_classification/resnet) the weights point to https://s3.amazonaws.com/onnx-model-zoo, how do we upload there? Or should we send the models to you and you guys upload them?

**Comment by prasanthpul** [comment]
We are looking at Git LFS so you would be able to submit on your own. But for now, you'll need to do a PR for the docs and send us the model package and it will be hosted on S3 or Azure Blob (https://onnxzoo.blob.core.windows.net/models/)

**Comment by bpinaya** [comment]
Great, is there an email? I'll try to finish the readme this week, I can also put in on google drive and post the link when I submit the PR I think. Thanks for the info

**Comment by ankkhedia** [comment]
@bpinaya Thanks for your contribution! you can share the google drive link here and I can put the model in S3 for you.
