### ISSUE TITLE
ValueError while executing imagenet_inference.ipynb

### ISSUE THREAD

**Issue by idilsulo** [onnx/models#113]
When I run imagenet_inference.ipynb with the SqueezeNet given in this [link](https://github.com/onnx/models/tree/master/models/image_classification/squeezenet), it works without encountering any issues. However, when I run the same Jupyter Notebook with the SqueezeNet given by this [link](https://github.com/onnx/models/tree/master/squeezenet), I get the following ValueError:

```
ValueError: You created Module with Module(..., data_names=['data']) but input with name 'data' is not found in symbol.list_arguments(). Did you mean one of:
	data_0
	conv1_w_0
	conv1_b_0
	fire2/squeeze1x1_w_0
	fire2/squeeze1x1_b_0
	fire2/expand1x1_w_0
	fire2/expand1x1_b_0
	fire2/expand3x3_w_0
	fire2/expand3x3_b_0
	fire3/squeeze1x1_w_0
	fire3/squeeze1x1_b_0
	fire3/expand1x1_w_0
	fire3/expand1x1_b_0
	fire3/expand3x3_w_0
	fire3/expand3x3_b_0
	fire4/squeeze1x1_w_0
	fire4/squeeze1x1_b_0
	fire4/expand1x1_w_0
	fire4/expand1x1_b_0
	fire4/expand3x3_w_0
	fire4/expand3x3_b_0
	fire5/squeeze1x1_w_0
	fire5/squeeze1x1_b_0
	fire5/expand1x1_w_0
	fire5/expand1x1_b_0
	fire5/expand3x3_w_0
	fire5/expand3x3_b_0
	fire6/squeeze1x1_w_0
	fire6/squeeze1x1_b_0
	fire6/expand1x1_w_0
	fire6/expand1x1_b_0
	fire6/expand3x3_w_0
	fire6/expand3x3_b_0
	fire7/squeeze1x1_w_0
	fire7/squeeze1x1_b_0
	fire7/expand1x1_w_0
	fire7/expand1x1_b_0
	fire7/expand3x3_w_0
	fire7/expand3x3_b_0
	fire8/squeeze1x1_w_0
	fire8/squeeze1x1_b_0
	fire8/expand1x1_w_0
	fire8/expand1x1_b_0
	fire8/expand3x3_w_0
	fire8/expand3x3_b_0
	fire9/squeeze1x1_w_0
	fire9/squeeze1x1_b_0
	fire9/expand1x1_w_0
	fire9/expand1x1_b_0
	fire9/expand3x3_w_0
	fire9/expand3x3_b_0
	conv10_w_0
	conv10_b_0
```

What might be the reason for this?

**Comment by ankkhedia** [comment]
@idilsulo The problem could be due to the input layer name getting used in the inference notebook. The input layer name is data in notebook whereas it is data_0 for this model-https://github.com/onnx/models/tree/master/squeezenet. Try changing the notebook input name to data_0 when running this model and this should work.

**Comment by idilsulo** [comment]
I have changed 'data' to 'data_0' as you have suggested. Yet, the problem remains.

**Comment by ankkhedia** [comment]
@idilsulo You can continue your work using the other squeezenet. Can you post the error log? Did you get same error?

**Comment by ankkhedia** [comment]
Hi @idilsulo 
You can use following code snippet in the notebook while loading the model.
```python
from mxnet.contrib import onnx as onnx_mxnet
if len(mx.test_utils.list_gpus())==0:
    ctx = mx.cpu()
else:
    ctx = mx.gpu(0)
# Load module
metadata = onnx_mxnet.get_model_metadata(model_path)
data_names = [input_name[0] for input_name in metadata.get('input_tensor_data')]
mod = mx.mod.Module(symbol=sym, data_names=data_names, context=mx.cpu(), label_names=None)
mod.bind(for_training=False, data_shapes=[(data_names[0], (1,3,224,224))], label_shapes=None)
#mod = mx.mod.Module(symbol=sym,data_names= ['data_0'], context=ctx, label_names=None)
#mod.bind(for_training=False, data_shapes=[('data_0', (1,3,224,224))], 
#         label_shapes=mod._label_shapes)
mod.set_params(arg_params, aux_params, allow_missing=True, allow_extra=True)
```
However, I am not sure about accuracy of the above model as it is not mentioned in the model description neither any preprocessing/post processing steps described. 
I would suggest you to use the first model itself if that works for you.

**Comment by idilsulo** [comment]
Hello @ankkhedia 
There is definitely a problem about the accuracies computed with respect to the code segment that you have mentioned, since it predicts the following probabilities regardless of whether I give the "kitten.jpg" or the "tabby.jpg" as an input:
```
class=n15075141 toilet tissue, toilet paper, bathroom tissue ; probability=1.000000
class=n02319095 sea urchin ; probability=1.000000
class=n02395406 hog, pig, grunter, squealer, Sus scrofa ; probability=1.000000
class=n02391049 zebra ; probability=1.000000
class=n02389026 sorrel ; probability=1.000000
```

I wanted to know why this is the case, since we will be keeping the models in the ONNX format for a project that I currently work in; which also means that I only use the pre-trained models given in this repository for test purposes. Therefore, it is important for us to not encounter such an issue for our own models.

**Comment by idilsulo** [comment]
As I have mentioned above, I am not specifically interested in this SqueezeNet model since I will be creating my own models with ONNX standard. 

I will also check the other issues related to this problem that mentions duplicate models.
