### ISSUE TITLE
Illegal reshape() in model zoo?

### ISSUE THREAD

**Issue by mathisdon** [onnx/models#114]
I believe there is an illegal reshape() operator in a model zoo model.

The model [emotion_ferplus](https://github.com/onnx/models/tree/master/emotion_ferplus) has a reshape() node called "Times622_reshape0" whose input tensor has shape (N, 256, 4, 4) where N is batch size, and it has the shape argument (1, 4096). 

That would imply that the output tensor has shape (1, 4096). But that can't be right, because that throws away the batch size N. The correct shape parameter should either be (0, 4096) or (-1, 4096) so that N is retained.

Can anyone comment on this please?

Thanks

**Comment by ebarsoum** [comment]
@mathisdon which version of the model? 1.3 takes (1,1,64,64) as input.

**Comment by mathisdon** [comment]
Yes it's version 1.3 of the model.

Ok, maybe I see the answer. Is the batchsize, N, for this model actually equal to 1? If so, that would explain it, as the Reshape node that I'm talking about (node 42) reshapes its (1, 256, 4, 4) input to (1, 4096) in that case.

Does that imply that this model can only be run on single inputs at a time? 

Thanks

**Comment by ebarsoum** [comment]
Most models in the zoo has batch value of 1, so yes you will need to run a single input at a time.

**Comment by mathisdon** [comment]
ok thank you
