### ISSUE TITLE
Can't evaluate Onnx 1.2 models in CNTK 2.6

### ISSUE THREAD

**Issue by YanYas** [onnx/models#115]
Using Yolo v2 downloaded from the [model zoo](https://github.com/onnx/models/tree/master/tiny_yolov2), CNTK manages to load the model but on evaluation, it returns an error:

> ToBatchAxis4441 ToBatchAxisNode operation can only operate on tensor without minibatch data (no layout)

Any ideas why?

**Comment by ebarsoum** [comment]
Please move this issue to CNTK github.

**Comment by YanYas** [comment]
Done https://github.com/Microsoft/CNTK/issues/3507#issuecomment-440028754
I'm not sure who this issue should be directed since these projects, from the outside, seem interlinked.
