### ISSUE TITLE
emotion_ferplus model seems erroneous

### ISSUE THREAD

**Issue by delzac** [onnx/models#117]
Hi,

i was running the emotion_ferplus model on CNTK. It seems like no matter what image i put in, the most probably emotion is always [0, 3, 1, 2, 4, 7, 6, 5] in those order.

I preprocess my image like the following:
```
def preprocess(image_path):
    img = Image.open(image_path)
    img = img.resize((64, 64), Image.ANTIALIAS)
    img_data = rgb2grey(np.array(img))[None, None, ...]
    return img_data
```

Emotion is calculated using argsort and softmax.

**Comment by ebarsoum** [comment]
@delzac what is in the input image? The input to this model should be the square output of a face detector.

**Comment by delzac** [comment]
Thanks for highlighting! I tried again by manually cropping the faces out by hand, adn it didn't change the output (softmax score) materially.

I fed in also feed in a completely white image (a 1x1x64x64 array of ones) and that didn't change the softmax results materially too compared to the other face images.

It doesn't seem like the problem is with not using the output of a face detector.

**Comment by delzac** [comment]
Thanks a lot for the confirmation! Your tutorial is really helpful!
