### ISSUE TITLE
BatchNormalization parameter "consumed_inputs"

### ISSUE THREAD

**Issue by Roshrini** [onnx/models#13]
`resnet` model provides following attributes for BatchNormalization operator: 
{u'is_test': 1L, u'epsilon': 1.0000000656873453e-05, u'consumed_inputs': (0L, 0L, 0L, 1L, 1L)})

Can someone explain what is `consumed_inputs`? I couldn't find it's explanation in [onnx documentation about BatchNormalization operator](https://github.com/onnx/onnx/blob/master/docs/Operators.md#BatchNormalization).
@bddppq

**Comment by houseroad** [comment]
It's a hint for in-place operator. It is not recorded in the official docs yet.

**Comment by houseroad** [comment]
We have removed all the consumed_inputs already.

**Comment by spandantiwari** [comment]
Shufflenet model still seems to have `consumed_inputs` attributes (https://github.com/onnx/models/issues/35)

**Comment by Ac2zoom** [comment]
When it's cited as required in opset 1, does that mean it can be fed as an empty input, or some random 1 dimensional vector?
