### ISSUE TITLE
bert pretrained model

### ISSUE THREAD

**Issue by batwicket** [onnx/models#130]
hi..

I'm having difficulty determining the ONNX input arguments for a bert pretrained model. The case is documented using a slight variant of a standard example from HuggingFace's PyTorch project at [StackOverflow](https://stackoverflow.com/questions/54220042/how-do-you-generate-an-onnx-representation-of-a-pytorch-bert-pretrained-neural-n). Probably a minute or two to someone that is familiar with the interface.

Thanks!

**Comment by WilliamTambellini** [comment]
cf
https://github.com/onnx/models/pull/190

**Comment by tianleiwu** [comment]
For PyTorch, example of exporting ONNX model and inference using ONNX Runtime:
   https://github.com/tianleiwu/pytorch-pretrained-BERT/blob/master/examples/run_classifier.py

The export code is like:
        torch.onnx.export(model,
                          (dummy_input0, dummy_input1, dummy_input2),
                          onnx_file,
                          input_names = ["input_ids", "input_mask", "segment_ids"],
                          output_names = ["output"],
                          verbose=True)

**Comment by askhade** [comment]
@batwicket : Closing this issue based on the above responses. Please reopen this or create a new one if this is still an issue

**Comment by devdev999** [comment]
> For PyTorch, example of exporting ONNX model and inference using ONNX Runtime:
> https://github.com/tianleiwu/pytorch-pretrained-BERT/blob/master/examples/run_classifier.py
> 
> The export code is like:
> 
> ```
>         device = torch.device("cpu")
>         model.to(device)
>         dummy_input0 = torch.LongTensor(args.eval_batch_size, args.max_seq_length).to(device)
>         dummy_input1 = torch.LongTensor(args.eval_batch_size, args.max_seq_length).to(device)
>         dummy_input2 = torch.LongTensor(args.eval_batch_size, args.max_seq_length).to(device)
>         torch.onnx.export(model,
>                           (dummy_input0, dummy_input1, dummy_input2),
>                           onnx_file_name,
>                           input_names = ["input_ids", "input_mask", "segment_ids"],
>                           output_names = ["output"],
>                           verbose=True)
> ```

I am getting "IndexError: index out of range in self" when I attempt to export a model from pytorch-pretrained-bert using this, are models trained using the library supported for export with this method?

**Comment by tianleiwu** [comment]
@devdev999, No, some models trained by PyTorch cannot be exported to ONNX. Popular model like BERT and gpt2 are fine. The above example script is for model with three inputs (in forward function) and one output. If your model have different numbers of inputs or outputs, you need change the script accordingly. 

If you are using [huggingface transformers](https://github.com/huggingface/transformers), there is a script [convert_graph_to_onnx.py](https://github.com/huggingface/transformers/blob/master/src/transformers/convert_graph_to_onnx.py) for exporting model to onnx. You can try it on a pretrained model.

**Comment by KellyZhang2020** [comment]
@devdev999 Have you solved this problem？I have the same problem，and how did you finally convert the bert pretrained model to onnx model? Thanks a lot！
