### ISSUE TITLE
Converting input_0.pb files to floats in c#

### ISSUE THREAD

**Issue by YanYas** [onnx/models#131]
Hi, I'm trying to infer the MNIST (and others) model with my input. I'm not sure about the results so I would like to read the data from the .pb that comes with it and inspect the data to get an understanding of the relationship between the input and output of my data to know that it is reliable (or not).

However, so far I have been unable to deserialize the .pb files successfully. Is there a guide to reading back the raw data from these files? I've had a look at the onnx.proto2 and onnx.in.proto files in the onnx/onnx repo but in neither case was I able to understand what is going on in the header of the stream.

So far the bytes seem to read 
`8-batchNum-8-channels-8-height-8-width-16-1-74-someNumber-someOtherNumber-beginningOfActualValues` but this will differ from one file to the next.

Some guidance would be very appreciated

**Comment by prasanthpul** [comment]
Take a look at https://github.com/onnx/models#usage- for example on how to read the .pb files containing sample data that come with the models.

**Comment by YanYas** [comment]
Hi and thanks @prasanthpul. The trouble is I'd like to emulated the "tensor.ParseFromString" function in c#. I'm not using the onnx runtime but CNTK, which doesn't have a function for deserializing the pb files.

**Comment by snnn** [comment]
Did you try this lib:
https://developers.google.com/protocol-buffers/docs/csharptutorial

**Comment by YanYas** [comment]
Got there eventually. For those interested you need to compile c# classes .cs file from the [onnxproto3 ](https://github.com/onnx/onnx/blob/master/onnx/onnx.proto3)file using this [little compiler program.](https://github.com/protocolbuffers/protobuf/releases/tag/v3.7.0) (in my case _protoc-3.7.0-win64.zip_) This class, used in conjunction with [Google protocol ](https://www.nuget.org/packages/Google.Protobuf/) allows you to read data back from pb files correctly.
