### ISSUE TITLE
ArcFace model csharp InferenceSession

### ISSUE THREAD

**Issue by MitchVonk** [onnx/models#135]
Following the steps of the csharp Inference Example I'm trying to implement the ArcFace model.
Doing the same thing with Emotion FerPlus model does work, however the following error occurs for the ArcFace model and I am clueless:

' [ErrorCode:Fail] c:\agent_work\6\s\onnxruntime\core\providers\cpu\math\element_wise_ops.h:353 onnxruntime::BroadcastIterator::Init axis == 1 || axis == largest was false. Attempting to broadcast an axis by a dimension other than 1. 64 by 112 '

This error happens when I Run a InferenceSession. On line 154 of InferenceSession.cs the status returned is non Zero (64 according to the error message) :
IntPtr status = NativeMethods.OrtRun(
this._nativeHandle,
IntPtr.Zero, // TODO: use Run options when Run options creation API is available
// Passing null uses the default run options in the C-api
inputNames,
inputTensors,
(ulong)(inputTensors.Length), /* TODO: size_t, make it portable for x86 arm _/ outputNamesArray, (ulong)outputNames.Count, /_ TODO: size_t, make it portable for x86 and arm _/ outputValueArray /_ An array of output value pointers. Array must be allocated by the caller */
);

**System information**

* Windows
* Microsoft.ML.OnnxRunetime version 0.2.1

**Comment by snnn** [comment]
#91

**Comment by snnn** [comment]
Hi @MitchVonk 
Is your problem solved?

**Comment by MitchVonk** [comment]
Downloaded the new model and it all works fine now! Thanks though!
