### ISSUE TITLE
Does the test data only have one sample in each pb file?

### ISSUE THREAD

**Issue by leimao** [onnx/models#137]
Hi,
I am downloading onnx models together with its test data. I want to confirm if in each pb file, the data is only corresponding to one single sample. For example, the output pb file for squeezenet is 4KB, which matches to the size of 1000 floating point values. The squeezenet also outputs probabilities for 1000 objects. 
Best,
Lei

**Comment by snnn** [comment]
As far as i can see, yes.

**Comment by leimao** [comment]
Thanks. I wish the pb file could contain more samples.

**Comment by snnn** [comment]
Not just a data problem. Most models do not support that.

**Comment by leimao** [comment]
> Not just a data problem. Most models do not support that.

Could you please elaborate on that? I am new to ONNX. Do you mean ONNX model only support batch size 1 for inference?

**Comment by snnn** [comment]
> Do you mean ONNX model only support batch size 1 for inference
No.

Run this script with your model
```python
import onnx
import sys

from onnx import ModelProto
from google.protobuf import text_format

proto = ModelProto()

f = open(sys.argv[1], "rb")
proto.ParseFromString(f.read())
f.close()
for input in proto.graph.input:
  print(input)

print('=========================')

for input in proto.graph.output:
  print(input)
```

It will print out the model's input/output shape.
If the shape is something like:
```
shape {
      dim {
        dim_value: 4
      }
    }
```
It doesn't support mini-batch.
On the other hand, it can support it only when the first dimension doesn't have a  dim_value.
