### ISSUE TITLE
caffe2 models for opset11

### ISSUE THREAD

**Issue by snnn** [onnx/models#141]
Hi,

I think we need to update the models converted from caffe2.
Like:
https://github.com/onnx/models/tree/master/bvlc_alexnet

Because the latest ONNX master code, is using opset 10.
Either we change 
```
master: https://s3.amazonaws.com/download.onnx/models/opset_9/bvlc_alexnet.tar.gz
```
To
```
master: https://s3.amazonaws.com/download.onnx/models/opset_10/bvlc_alexnet.tar.gz
```
Or, 
```
1.4 : https://s3.amazonaws.com/download.onnx/models/opset_9/bvlc_alexnet.tar.gz
```

**Comment by vinitra** [comment]
Addressed ONNX model Opset 9 discrepancies with the new Git LFS format (#271).  Will update opset 10 versions soon. Opset 11 has not been uploaded yet.
