### ISSUE TITLE
model checker raises ValidationError for ResNet-18 from model zoo

### ISSUE THREAD

**Issue by mnboos** [onnx/models#146]
See: https://github.com/pytorch/pytorch/issues/9375

I tried the ResNet-18 (https://github.com/onnx/models/tree/master/models/image_classification/resnet) with the model checker:

```python
>>> import onnx
>>> import onnx.checker
>>> onnx_model = onnx.load(r"C:\Users\bmar\Downloads\resnet18v1.onnx")
>>> onnx.checker.check_model(onnx_model)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\bmar\AppData\Local\Continuum\miniconda3\lib\site-packages\onnx\checker.py", line 77, in check_model
    C.check_model(model.SerializeToString())
onnx.onnx_cpp2py_export.checker.ValidationError: Input index 3 must be set to consumed for operator BatchNormalization

==> Context: Bad node spec: input: "resnetv15_conv0_fwd" input: "resnetv15_batchnorm0_gamma" input: "resnetv15_batchnorm0_beta" input: "resnetv15_batchnorm0_running_mean" input: "resnetv15_batchnorm0_running_var" output: "resnetv15_batchnorm0_fwd" name: "resnetv15_batchnorm0_fwd" op_type: "BatchNormalization" attribute { name: "epsilon" f: 1e-05 type: FLOAT } attribute { name: "momentum" f: 0.9 type: FLOAT } attribute { name: "spatial" i: 0 type: INT }
```

Why does this fail with a model officially available in the model zoo? Is it safe to just not check models? If so, then why is there even some model checking functionality?

**Comment by hannibalhuang** [comment]
@prasanthpul yes our team is currently working on developing the CI system, checker could be included in the system

**Comment by abhinavs95** [comment]
Hi @mnboos I am not able to reproduce your error. I am using a mac and the your test works fine. It looks like you are using windows. Unfortunately I do not have a windows machine to test on.

Could you provide which onnx version you are using? I am using 1.4.1

**Comment by mnboos** [comment]
Ohoh, apologies! For some reason, I was still using an older version. After upgrading to 1.4.1 the error is gone. Thanks and sorry for wasting your time!
