### ISSUE TITLE
ONNX Model of `Tiny YOLOv2` violate Naming Convension

### ISSUE THREAD

**Issue by nomaddo** [onnx/models#147]
In the model of TINY_YOLOv2, the root node has name "15fb3d9ea39f4068ad44a49de20faedc", which violate the following specification.
https://github.com/onnx/models/tree/master/tiny_yolov2

> All names MUST adhere to C identifier syntax rules.
https://github.com/onnx/onnx/blob/master/docs/IR.md#names-within-a-graph

**Comment by prasanthpul** [comment]
@EmmaNingMS please take a look at why it was converted this way

**Comment by jiafatom** [comment]
@nomaddo I just updated the tiny yolov2 model, can you please try again?

**Comment by nomaddo** [comment]
Thanks. I checked all IDs of `Model.onnx` on the page of tiny_yolov2 are correct.
