### ISSUE TITLE
Detection Quality of SSD model

### ISSUE THREAD

**Issue by saurabh-shandilya** [onnx/models#165]
I have been trying to reproduce the mAP score of 0.195 with COCO 2017 validation dataset for the model at https://github.com/onnx/models/tree/master/ssd with onnruntime as backend. I am pre-processing the input image as described in the link. 

Here are the details of my environment 
a) python3.6, on windows 
b) onnx version 1.5 (opset 10)
c) onnx runtime version 0.4.0 (compatible with opset 10)

Before running the whole dataset I tried to verify the model with test_data_set_0 and results were matching upto 5th decimal places. 

However, when I tried to run the model over the whole COCO-2017 dataset I could only get a mAP score of 0.002. I have verified the coco mAP score evaluation script based on example in https://github.com/cocodataset/cocoapi/blob/master/PythonAPI/pycocoEvalDemo.ipynb, so I have no reason to suspect the script.

When I tried to run model for a single image the first image in COCO2017 validation dataset 000000000139.jpg categories looked too off (after adding an offset 1 for background class)
[58 64 60  2 58 60 62 62  2 77 62 60 60 62 60 62 62 62 58  2 62 60 60 62
 58 58 62 58 62 58 62 62 62 75 58 58 60 58 75 62 58 58 62 58 58 60 62 62
 71 58 60 62 58 62 60  2 58 77 75 75  2 58 58  2 60 62 75 58 58 43 60 75
 60 75 62 58 58 62 62 58 75  2 75 58 62 60 58  2 58 60 58 60 64 58  2 75
 41 58 62 62 60 62 62 60 58 62 75 60 75 62 75 75 62 62 75 58 62 58 75 62
  2 75 58 76 62 62 58  2 62 62 62 62 58 75 75 58 62 58 58  2  2 58 75 58
 75 75 58  2 60 60 58 58 58 41 62  2 62 75 75  2  2 77 75 58  2  2  2 45
 75 60 58 64 60 60  2 58 62  2 71 58 58 58 62 58 58 60 75 60 58 64 58 58
 58 62 58 60 60 60 64  2]

The ground truth predominantly has 64,72,62,1.  Finally I get a mAP score of 0 for this single image. 

I am interpreting the 4 co-ordinates coming out of the model as (ymin, xmin, ymax, xmax), scaling it up by (img_height, img_width, img_height, img_width) and then converting it to coco detection format of (xmin, ymin, width, height).

Is there anything that I am doing wrong or is something wrong with the model?

**Comment by prasanthpul** [comment]
@hariharans29

**Comment by BowenBao** [comment]
hi @saurabh-shandilya, I got the following result for your example image, doesn't seem very off. Could you share how you convert the results to coco format?

![sample-det](https://user-images.githubusercontent.com/9376104/58924096-4b4ea480-86f7-11e9-9170-6888563fcd48.jpg)

**Comment by saurabh-shandilya** [comment]
@BowenBao 

Thanks for a quick response. Here is my code 

```
import numpy as np
import onnx
import os
import glob
from onnxruntime.backend.backend import OnnxRuntimeBackend as backend
from PIL import Image
from object_detection.metrics import coco_tools as coco_tools
from object_detection.utils import label_map_util as label_map_util 
from onnx import numpy_helper

def preprocess(img_path):
    input_shape = (1, 3, 1200, 1200)
    img = Image.open(img_path)
    width, height = img.size
    img = img.resize((1200, 1200), Image.BILINEAR)
    img_data = np.array(img)
    img_data = np.transpose(img_data, [2, 0, 1])
    img_data = np.expand_dims(img_data, 0)
    mean_vec = np.array([0.485, 0.456, 0.406])
    stddev_vec = np.array([0.229, 0.224, 0.225])
    norm_img_data = np.zeros(img_data.shape).astype('float32')
    for i in range(img_data.shape[1]):
        norm_img_data[:,i,:,:] = (img_data[:,i,:,:]/255 - mean_vec[i]) / stddev_vec[i]     
    return norm_img_data, width, height

model = onnx.load(args.model)
categories = label_map_util.create_categories_from_labelmap(args.label)

pathlist = glob.glob(os.path.join(args.data_dir, '*.jpg'))
inputs_num = len(pathlist)
print(inputs_num)

image_ids = []
detection_boxes_list = []
detection_classes_list = []
detection_scores_list = []

for input_file in pathlist:
    print(input_file)
    input_image, width, height = preprocess(input_file)        
    scale_box=[height, width, height, width] 
    out_det=backend.run_model(model, input_image)    
    img_id = int( os.path.splitext(  os.path.basename(input_file) )[0])    
    curr_bbox = np.squeeze(out_det[0])
    curr_bbox =  np.multiply (curr_bbox,scale_box)
    curr_class = np.squeeze(out_det[1]+1)
    curr_score = np.squeeze(out_det[2])  

    image_ids.append(img_id)
    detection_boxes_list.append(curr_bbox)
    detection_classes_list.append(curr_class)    
    detection_scores_list.append(curr_score)

coco_tools.ExportDetectionsToCOCO(image_ids, detection_boxes_list, detection_scores_list, detection_classes_list, categories, output_path=args.output)    
```

**Comment by BowenBao** [comment]
@saurabh-shandilya the output for this model is (xmin, ymin, xmax, ymax), could you update your script and see if that helps? We'll update the instructions to be more specific.

**Comment by saurabh-shandilya** [comment]
@BowenBao Finally I am able to get decent detection. For the first 100 images in val2017, I am getting a COCO mAP score of 0.252 (Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.252)

Changes needed were 
a) curr_bbox=curr_bbox1[:,[1,0,3,2]] (xmin, ymin, xmax, ymax) interpretation as you suggested. So I did
curr_bbox=curr_bbox[:,[1,0,3,2]] in the code above

b) class interpretation - This was tricky. I was expecting that class-ids would be in the range of (0,90). However, the lable_map file has got only 80 classes and index(in range [0-79]) and id (in range [1-90 with gaps in between]) are different apart from the background class-id. 
What worked was interpreting class output as index instead of idx.

It would be great if this could be added in the description of the model. 

I am currently running the inference on the complete val2017 dataset and will report mAP score once it finishes.

**Comment by saurabh-shandilya** [comment]
@BowenBao Here is what I am getting now. Not much difference between 0.196 and 0.195, so I guess we can close this. Thanks again for quick responses.

 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.196
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.375
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.180
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.114
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.256
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.227
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.196
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.318
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.341
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.171
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.404
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.411
