### ISSUE TITLE
Constant Folding Possibility in SSD ONNX Model

### ISSUE THREAD

**Issue by saurabh-shandilya** [onnx/models#166]
The SSD model at https://github.com/onnx/models/tree/master/ssd  has several instances of Reshape getting a shape input which can be converted to a  constant e.g. 

![subgraph](https://user-images.githubusercontent.com/40773275/59052804-cb365500-8844-11e9-90de-c01b29b335c6.jpg)

Is it possible to fold such sub-graphs which result in constant tensors either in pytorch or in ONNX ? Does current ONNX optimizer has any available pass to do this? If not is it possible to have a model which is already constant folded.

Thanks!

**Comment by prasanthpul** [comment]
Your inference engine will usually do the applicable optimizations. ONNX Runtime can do constant folding, for example

**Comment by saurabh-shandilya** [comment]
@prasanthpul 
I am working with Glow, which doesn't support this kind of folding at this time. Does ONNX optimizer support it?

**Comment by saurabh-shandilya** [comment]
Closing this thread assuming answer is "No solution at the moment". Will look to add this in Glow. Closing this.
