### ISSUE TITLE
Add Retinanet object detection model

### ISSUE THREAD

**Issue by SnowRipple** [onnx/models#173]
RetinaNet is one of the most widely (if not the most popular) used detection model for over a year now. 

Can you provide an ETA when it will be available through ONNX?

**Comment by SnowRipple** [comment]
Any update? It's been over a month now..

**Comment by piotr-anyvision** [comment]
Onnx team promised to support all main detection ops before the 1.6 release, but still no example of Retinanet working even though 1.6 was released 9 days ago? A little disappointed..
