### ISSUE TITLE
How to create input_0.pb?

### ISSUE THREAD

**Issue by nxp-xl** [onnx/models#175]
Hello, 

I converted some tensorflow models to ONNX format and inference them with onnx runtime, but when I using onnx_test_runner to test this model, I did not know how to create the input_0.pb and output_0.pb, so is there a document to describe this? Thanks.

**Comment by rpaner** [comment]
Hello, I have the same question now. Is there any easy way to generate the input_0.pb and output_0.pb files from pytorch? Thanks

**Comment by virajwad** [comment]
Same question!
