### ISSUE TITLE
faster rcnn onnx model too complicated, cao your simplifier?

### ISSUE THREAD

**Issue by 92ypli** [onnx/models#187]
we use the Netron tool vis the faster rcnn onnx model, but we get too complex, can your simplifier?

![image](https://user-images.githubusercontent.com/22673185/62110884-f50a7600-b2e1-11e9-8e7c-48e6034d5f02.png)

**Comment by jcwchen** [comment]
Unfortunately, this faster-RCNN model originally consists of a lot of layers. If you think it is hard to traverse such a huge model, you can use ctrl+F to find the target node. IMI, it's not a question for ONNX Model Zoo. Close it now. Please reopen it if you still have other questions. Thanks.
