### ISSUE TITLE
Visualize Input Image for Tiny YOLOv2

### ISSUE THREAD

**Issue by RandyGaul** [onnx/models#198]
I tried opening up the test images that come with Tiny YOLOv2 just to see what the input images are, in Python. Here's the image in `test_data_set_0`.

![image](https://user-images.githubusercontent.com/1919825/63064004-0cd22480-beb4-11e9-81be-1d9c4cd36c8e.png)

Below is the code I used to save the image to disk. Would this be the correct way to load up the test data? There seems to be a stride problem, but I can't seem to figure out where the error might be. Could anyone help visualize the input images saved within the `.pb` test input files?

```python
import numpy as np
import onnx
import os
import glob
import onnxruntime

from onnx import numpy_helper

from PIL import Image

test_data_dir = 'test_data_set_0'

# Load inputs
inputs = []
inputs_num = len(glob.glob(os.path.join(test_data_dir, 'input_*.pb')))
for i in range(inputs_num):
    input_file = os.path.join(test_data_dir, 'input_{}.pb'.format(i))
    tensor = onnx.TensorProto()
    with open(input_file, 'rb') as f:
        tensor.ParseFromString(f.read())
    inputs.append(numpy_helper.to_array(tensor))
    print(numpy_helper.to_array(tensor))
    data = numpy_helper.to_array(tensor)[0] # 1x3x416x416
    data = np.transpose(data, (1, 2, 0)) # 416x416x3
    print(type(data))
    print(data.dtype)
    print(data.shape)
    # rescaled = ((data - data.min()) / data.max()) * 255.0
    print("max and min ", data.min(), data.max())
    img = Image.fromarray(data.astype(np.uint8), 'RGB')
    img.save('img.png', 'PNG')
```

**Comment by prasanthpul** [comment]
The test data for models is just some test data to validate input tensors against output tensors. It is not required to be a proper image (as a person would define it). You should try running your own image through the model.

**Comment by RandyGaul** [comment]
Ended up just messing with a different net that had better documentation. My best guess it the test image was encoded as shown in the above post with an incorrect stride.
