### ISSUE TITLE
Same node output name in densenet121

### ISSUE THREAD

**Issue by linkerzhang** [onnx/models#2]
In the net, it has two nodes with same output (the name is not unique, check below). This is not a valid model, right?
 node {
    input: "conv1"
    input: "conv1/bn_scale"
    input: "conv1/bn_bias"
    input: "conv1/bn_mean"
    input: "conv1/bn_var"
    output: "conv1/bn"
    name: ""
    op_type: "SpatialBN"
    attribute {
      name: "is_test"
      i: 1
    }
    attribute {
      name: "epsilon"
      f: 1e-05
    }
    attribute {
      name: "consumed_inputs"
      ints: 0
      ints: 0
      ints: 0
      ints: 1
      ints: 1
    }
  }

node {
    input: "conv1/bn_internal"
    input: "conv1/bn_b"
    output: "conv1/bn"
    name: ""
    op_type: "Add"
    attribute {
      name: "broadcast"
      i: 1
    }
    attribute {
      name: "axis"
      i: 1
    }
  }

**Comment by bddppq** [comment]
It's valid, there can be multiple ops writing to the same output tensor. Latter op just overwrites the value written by the former ones.

**Comment by linkerzhang** [comment]
so we're assuming that all nodes in a model file are in topological order? feel like keep all names unique may be a better way so that nodes could hook up with each other with names. Thoughts?

**Comment by bddppq** [comment]
Nodes in a graph are topological sorted. Could you elaborate how unique name is better regarding to connecting nodes in a graph?
Reusing names (which implies reusing tensors/blobs) is more memory efficient.

**Comment by linkerzhang** [comment]
Thank you for confirmation!
In my opinion, reusing tensors/blobs belongs to optimization layer if modularizing the stack. It should be transparent to the graph representation layer (Model protobuf and its c++ representation). Bundling optimization stuff in this layer is enforcing upper layer (different runtimes) doing things same way, which may not be the scope of an open standard..
In another scenario, when constructing a graph from scratch by calling c++ APIs, like, graph.AddNode(...), there's no way to figure out how to hook up the nodes with duplicate names since the topological order has not been created yet.

**Comment by bddppq** [comment]
Sounds to me "enforcing unique name" is the one that makes everyone doing thing the same way (it adds requirement to the models emitted by the frontends).

Forcing unique names means:
 - Frontends need to make sure the names are unique, they need to create additional dummy input/output tensors to achieve this
 - Backends need to reverse engineer the tensor references to achieve the optimization

Turning a graph with duplicated names into unique names can be easily done, while the order direction is much harder.

**Comment by yuanbyu** [comment]
For inference, I would consider that ONNX is just an SSA representation of pure functional computation. So it seems to me a good idea to require that the names be unique at this level of abstraction. If the names are not unique, we have to make sure that a model always produces the same result regardless of the execution order of the nodes.  Also, if the names are not unique, can the graph be cyclic?

**Comment by gramalingam** [comment]
I also think having unique names is a better choice. Otherwise, we need to make assumptions such as the that the list of nodes is sorted (in execution order), which introduces artificial needless execution ordering constraints. Or, we need to introduce extra "dependence" edges between nodes with same output-name, etc.

**Comment by linkerzhang** [comment]
Thank you all for the follow-up discussions! I noticed that the updated densenet121 does not have duplicate node output names n, so, we have the agreement that all node output names should be unique, and I'm closing this issue now.

**Comment by bddppq** [comment]
Yep, sorry I forgot to update here. As you have found out, all the models have been regenerated with unique output names.

**Comment by prasanthpul** [comment]
@bddppq Is the requirement that output nodes be named uniquely documented somewhere? in onnx.proto ideally
