### ISSUE TITLE
export SSD model to onnx

### ISSUE THREAD

**Issue by xonobo** [onnx/models#204]
The sample [ssd model](https://onnxzoo.blob.core.windows.net/models/opset_10/ssd/ssd.onnx) is said to be trained by [mlperf-training-ssd](https://github.com/mlperf/training/tree/edd7308f45e7bb25d32725de23a30b405484b93f/single_stage_detector/ssd). When I draw the the graph of onnx file I see these NonMaxSupression operators in the graph. The mlperf training code does not contain any NMS operator. How can I get this kind of SSD onnx export. Can you point me to a code exporting the sample ssd.onnx file.
 
![nms](https://user-images.githubusercontent.com/1115812/63846688-f5576900-c994-11e9-83a3-300e7c72d23e.jpg)

Here is the full drawing of the ssd.onnx. It is a dot file, added a pdf extension to drop here
[ssd.onnx.dot.pdf](https://github.com/onnx/models/files/3550355/ssd.onnx.dot.pdf)

**Comment by xonobo** [comment]
I found the [link](https://github.com/BowenBao/inference/tree/master/cloud/single_stage_detector/pytorch) but still have problems to get onnx export.

This is the error I get when I call the export_to_onnx.sh:

> Decoding time:  1.8393218517303467
> Traceback (most recent call last):
>   File "infer.py", line 297, in <module>
>     main()
>   File "infer.py", line 294, in main
>     eval_ssd_r34_mlperf_coco(args)
>   File "infer.py", line 276, in eval_ssd_r34_mlperf_coco
>     return coco_eval_export(ssd_r34, val_coco, cocoGt, encoder, inv_map, args.threshold,args.device,use_cuda)
>   File "infer.py", line 107, in coco_eval_export
>     import pytorch_tmp_patch
>   File "/home/bozkalayci/github/inference/cloud/single_stage_detector/pytorch/pytorch_tmp_patch.py", line 122, in <module>
>     from torch.onnx.symbolic import parse_args, log, _maybe_get_const, _is_value, scalar_type_to_pytorch_type, t, _unpack_list, index_select, _parse_arg
> ModuleNotFoundError: No module named 'torch.onnx.symbolic'
> 

I tried  pytorch1.2 and 1.1 but same output.

**Comment by xonobo** [comment]
The [docker](https://github.com/BowenBao/inference/blob/master/cloud/single_stage_detector/Dockerfile) uses torch 1.0.1.post2 but building the shared object by setup.py resulted in this error:

> 
> python setup.py build 
> running build
> running build_ext
> building 'lib.custom_ops' extension
> creating build/temp.linux-x86_64-3.6
> creating build/temp.linux-x86_64-3.6/home
> creating build/temp.linux-x86_64-3.6/home/bozkalayci
> creating build/temp.linux-x86_64-3.6/home/bozkalayci/github
> creating build/temp.linux-x86_64-3.6/home/bozkalayci/github/inference
> creating build/temp.linux-x86_64-3.6/home/bozkalayci/github/inference/cloud
> creating build/temp.linux-x86_64-3.6/home/bozkalayci/github/inference/cloud/single_stage_detector
> creating build/temp.linux-x86_64-3.6/home/bozkalayci/github/inference/cloud/single_stage_detector/pytorch
> creating build/temp.linux-x86_64-3.6/home/bozkalayci/github/inference/cloud/single_stage_detector/pytorch/csrc
> creating build/temp.linux-x86_64-3.6/home/bozkalayci/github/inference/cloud/single_stage_detector/pytorch/csrc/cpu
> gcc -pthread -B /opt/conda/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/bozkalayci/github/inference/cloud/single_stage_detector/pytorch/csrc -I/opt/conda/lib/python3.6/site-packages/torch/lib/include -I/opt/conda/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -I/opt/conda/lib/python3.6/site-packages/torch/lib/include/TH -I/opt/conda/lib/python3.6/site-packages/torch/lib/include/THC -I/opt/conda/include/python3.6m -c /home/bozkalayci/github/inference/cloud/single_stage_detector/pytorch/csrc/vision.cpp -o build/temp.linux-x86_64-3.6/home/bozkalayci/github/inference/cloud/single_stage_detector/pytorch/csrc/vision.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=custom_ops -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
> cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
> gcc -pthread -B /opt/conda/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/bozkalayci/github/inference/cloud/single_stage_detector/pytorch/csrc -I/opt/conda/lib/python3.6/site-packages/torch/lib/include -I/opt/conda/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -I/opt/conda/lib/python3.6/site-packages/torch/lib/include/TH -I/opt/conda/lib/python3.6/site-packages/torch/lib/include/THC -I/opt/conda/include/python3.6m -c /home/bozkalayci/github/inference/cloud/single_stage_detector/pytorch/csrc/cpu/nms_cpu.cpp -o build/temp.linux-x86_64-3.6/home/bozkalayci/github/inference/cloud/single_stage_detector/pytorch/csrc/cpu/nms_cpu.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=custom_ops -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
> cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
> In file included from /opt/conda/lib/python3.6/site-packages/torch/lib/include/ATen/ATen.h:9:0,
>                  from /opt/conda/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include/torch/types.h:3,
>                  from /opt/conda/lib/python3.6/site-packages/torch/lib/include/torch/script.h:3,
>                  from /home/bozkalayci/github/inference/cloud/single_stage_detector/pytorch/csrc/cpu/vision.h:4,
>                  from /home/bozkalayci/github/inference/cloud/single_stage_detector/pytorch/csrc/cpu/nms_cpu.cpp:2:
> /home/bozkalayci/github/inference/cloud/single_stage_detector/pytorch/csrc/cpu/nms_cpu.cpp: In lambda function:
> /home/bozkalayci/github/inference/cloud/single_stage_detector/pytorch/csrc/cpu/nms_cpu.cpp:71:46: error: invalid initialization of reference of type 'const at::Type&' from expression of type 'c10::ScalarType'
>    AT_DISPATCH_FLOATING_TYPES(dets.scalar_type(), "nms", [&] {
>                                               ^
> /opt/conda/lib/python3.6/site-packages/torch/lib/include/ATen/Dispatch.h:15:32: note: in definition of macro 'AT_DISPATCH_FLOATING_TYPES'
>      const at::Type& the_type = TYPE;                                         \
>                                 ^
> /home/bozkalayci/github/inference/cloud/single_stage_detector/pytorch/csrc/cpu/nms_cpu.cpp: In lambda function:
> /home/bozkalayci/github/inference/cloud/single_stage_detector/pytorch/csrc/cpu/nms_cpu.cpp:183:47: error: invalid initialization of reference of type 'const at::Type&' from expression of type 'c10::ScalarType'
>    AT_DISPATCH_FLOATING_TYPES(boxes.scalar_type(), "multi_label_nms", [&] {
>                                                ^
> /opt/conda/lib/python3.6/site-packages/torch/lib/include/ATen/Dispatch.h:15:32: note: in definition of macro 'AT_DISPATCH_FLOATING_TYPES'
>      const at::Type& the_type = TYPE;                                         \
>                                 ^
> error: command 'gcc' failed with exit status 1

**Comment by xonobo** [comment]
I added a symbolic.py file to torch/onnx folder. Here is the contrent of it
```
from torch.onnx.symbolic_opset7 import *
from torch.onnx.symbolic_opset8 import *
from torch.onnx.symbolic_opset9 import _cast_Int, _cast_Long, _shape_as_tensor, _convolution
from torch.onnx.symbolic_opset9 import *
from torch.onnx.symbolic_opset10 import *
from torch.onnx.symbolic_helper import _maybe_get_const, _is_value, _unpack_list, _parse_arg
from torch.onnx.symbolic_helper import *

torch.onnx.symbolic_helper._default_onnx_opset_version = 10
```

Succeeded to create the onnx file. I used pytorch 1.2.0

**Comment by kolingv** [comment]
Can you run the model on onnxruntime?

Follow the tutorial "export Pytorch model with custom op to ONNX and run it in ONNX Runtime" [here](https://github.com/onnx/tutorials/tree/master/PyTorchCustomOperator), and combine with corresponding cpp file here -> infer.py I've exported it to onnx sucessfully by registering custom NMS op in pytorch. However it was exported as multi_label_nms, not the desired 'NonMaxSupression' block defined in onnx operators.

While quoted from the tutorial mentioned above,
"You can export your custom operator using existing ONNX ops, or you can create custom ONNX ops to use. In both cases, you need to add the symbolic method to the exporter, and register your custom symbolic using torch.onnx.register_custom_op_symbolic" and "If you are using existing ONNX ops only, you do not need to go through this last step (register in onnxrutime)."

These words made me confused. I did exported to an existing ONNX op!

BTW, i made a model with onnx helper functions and then sucessfully run on onnxrutime. But append a NMS node to the existing graph didn't pass onnxruntime - report sth like no register NMS module.

I'm really confused how onnx match onnxruntime.

Really appreciate if u have any clues.
