### ISSUE TITLE
bidaf test data set question

### ISSUE THREAD

**Issue by jinz2014** [onnx/models#211]
The number of input and output files are not the same for bidaf model's test data set. There are four input files and two output files.  Is this expected ? 

Thanks

bidaf$ ls test_data_set_2
input_0.pb  input_1.pb  input_2.pb  input_3.pb  output_0.pb  output_1.pb

**Comment by askhade** [comment]
Yes this is expected.
This model takes 4 inputs and produces 2 outputs...Hence 4 inputs and 2 outputs in the test_data_set

![image](https://user-images.githubusercontent.com/6475296/84209452-03313300-aa6b-11ea-9f08-c04cba9fab41.png)
