### ISSUE TITLE
Add a warning/note/howto about git lfs in README.md

### ISSUE THREAD

**Issue by WilliamTambellini** [onnx/models#215]
Dear
More and more models in this repo are managed via git LFS.

$ git lfs ls-files
1cec14b36f - text/machine_comprehension/bert-squad/model/bertsquad10.onnx.tar.gz
2a2cbf9ffc - text/machine_comprehension/bert-squad/model/bertsquad8.onnx.tar.gz
d0b97f7807 - text/machine_comprehension/bert-squad/model/download_sample_10.tar.gz
9284809bd8 - text/machine_comprehension/bert-squad/model/download_sample_8.tar.gz
e3c6f442e1 - vision/style_transfer/fast_neural_style/models/opset8/candy.onnx
e6a40c8d1b - vision/style_transfer/fast_neural_style/models/opset8/candy.tar.gz
8547ad0196 - vision/style_transfer/fast_neural_style/models/opset8/mosaic.onnx
2b3090c84a - vision/style_transfer/fast_neural_style/models/opset8/mosaic.tar.gz
09fb31931c - vision/style_transfer/fast_neural_style/models/opset8/pointilism.onnx
e67096dba8 - vision/style_transfer/fast_neural_style/models/opset8/pointilism.tar.gz
bf13b62357 - vision/style_transfer/fast_neural_style/models/opset8/rain_princess.onnx
483c273fd3 - vision/style_transfer/fast_neural_style/models/opset8/rain_princess.tar.gz
31f8c5457a - vision/style_transfer/fast_neural_style/models/opset8/udnie.onnx
81768986c4 - vision/style_transfer/fast_neural_style/models/opset8/udnie.tar.gz
9d11a3529d - vision/style_transfer/fast_neural_style/models/opset9/candy.onnx
7647c08408 - vision/style_transfer/fast_neural_style/models/opset9/candy.tar.gz
fa646dedad - vision/style_transfer/fast_neural_style/models/opset9/mosaic.onnx
e7d395a1a2 - vision/style_transfer/fast_neural_style/models/opset9/mosaic.tar.gz
5ee2b8d4d6 - vision/style_transfer/fast_neural_style/models/opset9/pointilism.onnx
ceac242d7e - vision/style_transfer/fast_neural_style/models/opset9/pointilism.tar.gz
4162912e6f - vision/style_transfer/fast_neural_style/models/opset9/rain_princess.onnx
8c35f1d7c7 - vision/style_transfer/fast_neural_style/models/opset9/rain_princess.tar.gz
8656b6ce7d - vision/style_transfer/fast_neural_style/models/opset9/udnie.onnx
713f43d887 - vision/style_transfer/fast_neural_style/models/opset9/udnie.tar.gz
85f36ff88c - vision/super_resolution/sub_pixel_cnn_2016/model/super_resolution.onnx
5843ec9620 - vision/super_resolution/sub_pixel_cnn_2016/model/super_resolution_test_image.tar.gz
4c898d7860 - vision/super_resolution/sub_pixel_cnn_2016/super_resolution_test_image.gz

The README.md does not seem to mention that need for git lfs.

The question/proposal is to add at least a warning/note in order for the user to be aware:
- that some onnx files are 'just' lfs pointers files
- that they have to install the git lfs plugin if need be
- that they will have to enable lfs after cloning this repo
- that they would have to git lfs fetch the desired file(s) in order to be able to run some inference on the desired onnx file(s) avoiding to download GBs of files

Kind

**Comment by vinitra** [comment]
Thanks for the feedback @WilliamTambellini. We're planning to move all our models to git LFS for standardization. We will make sure to address these concerns in the README.
