### ISSUE TITLE
[BERT-Squad] Which onnx file to use

### ISSUE THREAD

**Issue by tmoreau89** [onnx/models#219]
On the following README: https://github.com/onnx/models/tree/master/text/machine_comprehension/bert-squad

We can download the model and sample file tarballs for `BERT-Squad` models expressed in opset 8/10. Untaring the tarballs shows 2 `.onnx` files in each uncompressed directory. For instance, `BERT-squad` opset 8  has a `bert8.onnx` and a `bertModel.onnx` file. They have similar sizes, 435882893B and 435883477B respectively.

Thanks in advance for some pointers @kundanapillari @prasanthpul

**Comment by vinitra** [comment]
This is currently resolved, as there is currently only one onnx model in each of the tar.gz files. Please re-open if you're facing this issue in the future.
