### ISSUE TITLE
YoloV3 ONNX model has non-specified input dimensions values

### ISSUE THREAD

**Issue by BarkenBark** [onnx/models#222]
### Problem:
When visualizing the YoloV3 ONNX model (https://github.com/onnx/models/tree/master/vision/object_detection_segmentation/yolov3) using Netron (https://lutzroeder.github.io/netron/), the dimensions of input_1 are given as float32[unk__576, 3, unk__577, unk__578], and the dimensions of image_shape are given as float32[unk_579, 2]. Similarly in Python, by accessing sess.get_inputs(), where sess is an InferenceSession loaded from yolov3.onnx, you obtain ['unk_576', 3, 'unk_577', 'unk_578'] for input_1, and ['unk_579', 2] for image_shape.

According to the documentation, one would expect the dimensions to be [1,3,416,416] and [1,2] respectively.

### Symptoms
This is problematic because:
- It seemingly prevents deployment with OnnxRuntime in C# (https://github.com/microsoft/onnxruntime)
- It seemingly prevents deployment with ML.NET in C# (https://github.com/dotnet/machinelearning)
- It is inconsistent with the README.md

Inference with an InferenceSession in the C# implementation of OnnxRuntime fails as an ArgumentOutOfRangeException is thrown when running the session:
> ◢ | $exception | {"Dimensions must be positive and non-zero\r\nParameter name: dimensions"} | System.ArgumentOutOfRangeException

### Issue with ONNX model or with C# OnnxRuntime?
I have not been able to find anything in the Onnx format specification which explains the 'unk_xxx' values. However, it is possible that such values are expected/have an interpretation that a Onnx backend should be able to handle, in which case my problem is not caused by a faulty ONNX model, but due to an issue ion the backend implementation.

### Details:
The Dimensions of the inputs obtained from session.InputMetaData in C#, where session is an instance of InferenceSession from Microsoft.ML.OnnxRuntime, are [-1,3,-1,-1] and [-1,2] respectively. 

Inference with the model works in the python implementation of OnnxRuntime.

The README.md for YoloV3 clearly specifies that the input should be (1x3x416x416) and (1x2) respectively. 

Inference in Python fails for inputs with shapes other than (1,3,416,416), which is expected from YoloV3.

The following is the code I used in C# to run inference with the model:

```C#
int gpuIndex = 0;
string modelPath = 'yolov3.onnx'
var session = new InferenceSession(modelPath, SessionOptions.MakeSessionOptionWithCudaProvider(gpuIndex));

// Create random input data tensors
int[] dim = {1,3,416,416};
float[] dummyInput = new float[dim[0]*dim[1]*dim[2]*dim[3]];
for (int i = 0; i < dummyInput.Length; i++)
{
    dummyInput[i] = 0.50f;
}
Tensor<float> inputImageTensor = new DenseTensor<float>(dummyInput, dim);
float[] dummyImageShape = new float[2];
dummyImageShape[0] = 416;
dummyImageShape[1] = 416;
int[] dim2 = {1, 2};
Tensor<float> imageShapeTensor = new DenseTensor<float>(dummyImageShape, dim2);

// Feed the input to the session and infer
var inputs = new List<NamedOnnxValue>()
{
    NamedOnnxValue.CreateFromTensor<float>("input_1", inputImageTensor),
    NamedOnnxValue.CreateFromTensor<float>("image_shape", imageShapeTensor)
};
session.Run(inputs);
`

**Comment by jiafatom** [comment]
@BarkenBark We convert yolov3 model from [here](https://github.com/qqwweee/keras-yolo3/). The keras model input is (?,?,?,3) and (?,2). ? stands for unknown dimension. This is why our onnx model comes up with ['unk_576', 3, 'unk_577', 'unk_578'] for input_1 (we use "channel first"), and ['unk_579', 2] for image_shape. The symbol here means different dimension values. 

We need make our onnx model behavior same as keras model. The keras model shape is (416, 416) that is fixed. So our model also need input shape be (1, 3, 416, 416). [Here](https://github.com/onnx/models/tree/master/vision/object_detection_segmentation/yolov3) mentions the preprocessing step to normalize the image shape.

When you do inference session in C#, are you using the shape (1, 3, 416, 416)? If you use the right shape, then it would be an onnxruntime issue for the failure.

**Comment by BarkenBark** [comment]
I verified that the shape of the input tensor in C# is (1,3,416,416) and the shape of the image shape tensor is (1,2). The program fails with the same error.
```C#
inputImageTensor.Dimensions.ToArray().ToList().ForEach(i => Console.WriteLine(i.ToString()));
`
The output of above code is 1, 3, 416, 416.

As I see it, there are two issues at hand: 1) The ONNX model specifies unknown dimensions on inputs but only works with inputs of a externally specified shape. 2) The C# OnnxRuntime is unable to handle unknown dimension sizes for dimensions other than the batch dimension.

Since the YoloV3 model only works with inputs of the specified shapes, it would be nice if this was reflected in the actual ONNX model hosted, but I understand that updating this might not be a priority. Feel free to close this issue if there is no plan to update the ONNX model in this light.

As for the C# OnnxRuntime, I will raise an issue in the OnnxRuntime repository explaining the issue.

Thank you.

**Comment by BarkenBark** [comment]
Turns out there is a known bug in OnnxRuntime which makes it unable to handle unknown dimension sizes (see https://github.com/microsoft/onnxruntime/issues/1770).

I still think the model should be updated such that the input shapes are not unknown for the reasons stated above, but if there is no plan to do so, please feel free to close this issue.

**Comment by jiafatom** [comment]
For 1), I agree there is some confusion here, but from converter point of view, the keras model itself specifies unknown dimension size, we have to make the onnx model input consistent with the keras model. For this particular yolov3 model, the input needs fixed, but when we convert the model, we don't get this information from the keras model itself.
2) Thanks for pointing out the onnxruntime bug, C# should handle unknown dimension sizes.

**Comment by yutimetha** [comment]
can any one share enitre code for loading  Yolov3 onnx model using Machine learning dot net model?
i am getting error is "Parameter name: Dimension { } in ONNX tensor cannot exceed the maximum of 32-bit signed integer."

please its too urgent

**Comment by yutimetha** [comment]
Can any one have code snippet for performing Object detection in Dot net using yolov3 Onnx model?

**Comment by gvashishtha** [comment]
@yutimetha there is an example in the comments of this blog post where the Yolov3 model was used: https://devblogs.microsoft.com/dotnet/announcing-ml-net-1-4-global-availability-machine-learning-for-net/#comment-4034

I also found this issue: https://github.com/dotnet/machinelearning/issues/4239 where someone had a similar problem to yours.

If the above examples are not helpful, please create an issue on the ML.NET repo (https://github.com/dotnet/machinelearning) and we will work through this.

**Comment by yutimetha** [comment]
@gvashishtha  thanks for your reply. I tried with the same link but not got success there is an issue with input and output parameter and any how i an not getting any clue for this.
