### ISSUE TITLE
Runtime error on Inference session Unet model converted from Pytorch

### ISSUE THREAD

**Issue by patmaasridharan** [onnx/models#249]
I have a custom UNet in pytorch and exported it to onnx model. That worked fine. On calling inference , there is problem with the optimizer. Below is the output.

>>> ort_session = onnxruntime.InferenceSession("saved_model/seg_R.onnx")
 [W:onnxruntime:, graph.cc:2412 CleanUnusedInitializers] Removing initializer 'up1.trans_conv.bias'. It is not used by any node and should be removed from the model.
[W:onnxruntime:, graph.cc:2412 CleanUnusedInitializers] Removing initializer 'up1.convr2.bn.num_batches_tracked'. It is not used by any node and should be removed from the model.
[W:onnxruntime:, graph.cc:2412 CleanUnusedInitializers] Removing initializer 'up2.convr1.bn.num_batches_tracked'. It is not used by any node and should be removed from the model.
 [W:onnxruntime:, graph.cc:2412 CleanUnusedInitializers] Removing initializer 'down3.convr1.bn.num_batches_tracked'. It is not used by any node and should be removed from the model.
[W:onnxruntime:, graph.cc:2412 CleanUnusedInitializers] Removing initializer 'down3.convr2.bn.num_batches_tracked'. It is not used by any node and should be removed from the model.
 [W:onnxruntime:, graph.cc:2412 CleanUnusedInitializers] Removing initializer 'up3.convr2.bn.num_batches_tracked'. It is not used by any node and should be removed from the model.
 [W:onnxruntime:, graph.cc:2412 CleanUnusedInitializers] Removing initializer 'up4.trans_conv.weight'. It is not used by any node and should be removed from the model.
 [W:onnxruntime:, graph.cc:2412 CleanUnusedInitializers] Removing initializer 'down1.convr1.bn.num_batches_tracked'. It is not used by any node and should be removed from the model.
 [W:onnxruntime:, graph.cc:2412 CleanUnusedInitializers] Removing initializer 'up1.convr1.bn.num_batches_tracked'. It is not used by any node and should be removed from the model.
 [W:onnxruntime:, graph.cc:2412 CleanUnusedInitializers] Removing initializer 'up4.trans_conv.bias'. It is not used by any node and should be removed from the model.
 [W:onnxruntime:, graph.cc:2412 CleanUnusedInitializers] Removing initializer 'up2.trans_conv.weight'. It is not used by any node and should be removed from the model.
 [W:onnxruntime:, graph.cc:2412 CleanUnusedInitializers] Removing initializer 'up1.trans_conv.weight'. It is not used by any node and should be removed from the model.
 [W:onnxruntime:, graph.cc:2412 CleanUnusedInitializers] Removing initializer 'down4.convr1.bn.num_batches_tracked'. It is not used by any node and should be removed from the model.
 [W:onnxruntime:, graph.cc:2412 CleanUnusedInitializers] Removing initializer 'center.0.bn.num_batches_tracked'. It is not used by any node and should be removed from the model.
 [W:onnxruntime:, graph.cc:2412 CleanUnusedInitializers] Removing initializer 'down2.convr2.bn.num_batches_tracked'. It is not used by any node and should be removed from the model.
 [W:onnxruntime:, graph.cc:2412 CleanUnusedInitializers] Removing initializer 'down1.convr2.bn.num_batches_tracked'. It is not used by any node and should be removed from the model.
 [W:onnxruntime:, graph.cc:2412 CleanUnusedInitializers] Removing initializer 'up2.convr2.bn.num_batches_tracked'. It is not used by any node and should be removed from the model.
 [W:onnxruntime:, graph.cc:2412 CleanUnusedInitializers] Removing initializer 'down4.convr2.bn.num_batches_tracked'. It is not used by any node and should be removed from the model.
 [W:onnxruntime:, graph.cc:2412 CleanUnusedInitializers] Removing initializer 'center.1.bn.num_batches_tracked'. It is not used by any node and should be removed from the model.
 [W:onnxruntime:, graph.cc:2412 CleanUnusedInitializers] Removing initializer 'up2.trans_conv.bias'. It is not used by any node and should be removed from the model.
 [W:onnxruntime:, graph.cc:2412 CleanUnusedInitializers] Removing initializer 'up3.convr1.bn.num_batches_tracked'. It is not used by any node and should be removed from the model.
 [W:onnxruntime:, graph.cc:2412 CleanUnusedInitializers] Removing initializer 'up3.trans_conv.bias'. It is not used by any node and should be removed from the model.
[W:onnxruntime:, graph.cc:2412 CleanUnusedInitializers] Removing initializer 'up3.trans_conv.weight'. It is not used by any node and should be removed from the model.
 [W:onnxruntime:, graph.cc:2412 CleanUnusedInitializers] Removing initializer 'down2.convr1.bn.num_batches_tracked'. It is not used by any node and should be removed from the model.
 [W:onnxruntime:, graph.cc:2412 CleanUnusedInitializers] Removing initializer 'up4.convr2.bn.num_batches_tracked'. It is not used by any node and should be removed from the model.
 [W:onnxruntime:, graph.cc:2412 CleanUnusedInitializers] Removing initializer 'up4.convr1.bn.num_batches_tracked'. It is not used by any node and should be removed from the model.
 [E:onnxruntime:, inference_session.cc:847 Initialize] Exception during initialization: /onnxruntime_src/onnxruntime/core/optimizer/optimizer_execution_frame.cc:73 onnxruntime::OptimizerExecutionFrame::Info::Info(const std::vector<const onnxruntime::Node*>&, const InitializedTensorSet&) [ONNXRuntimeError] : 1 : FAIL : Failed to find kernel for Neg
Stacktrace:

/lib/python3.6/site-packages/onnxruntime/capi/session.py", line 25, in __init__self._load_model(providers)
/lib/python3.6/site-packages/onnxruntime/capi/session.py", line 43, in _load_model self._sess.load_model(providers)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Exception during initialization: /onnxruntime_src/onnxruntime/core/optimizer/optimizer_execution_frame.cc:73 onnxruntime::OptimizerExecutionFrame::Info::Info(const std::vector<const onnxruntime::Node*>&, const InitializedTensorSet&) [ONNXRuntimeError] : 1 : FAIL : Failed to find kernel for Neg

Does anyone has idea, why onnx inference fails though the model check doesn't show any error? Any leads will be appreciable :)

Thank you.

**Comment by prasanthpul** [comment]
Can you file this in https://github.com/microsoft/onnxruntime/issues so that the right folks can take a look?
