### ISSUE TITLE
There is no test data for squeeze net

### ISSUE THREAD

**Issue by ThomasDelteil** [onnx/models#25]
There is only three folders with .pb files. It would be nice to have a .npz file as well.

**Comment by houseroad** [comment]
Actually, we support two types of test data, npz or proto, I will add the detailed explanation in README.md.

**Comment by michaelschwier** [comment]
Any updates on this? I still only find explanations about using npz test data [here].(https://github.com/onnx/models)

**Comment by houseroad** [comment]
https://github.com/onnx/models/pull/29, I have added the description here.

**Comment by houseroad** [comment]
The description is already included in the README.md
