### ISSUE TITLE
GPT-2 export with token_type_ids fails

### ISSUE THREAD

**Issue by santhoshkolloju** [onnx/models#251]
/Users/a617341/Desktop/Desktop/GPT-2/pytorch_pretrained_bert/modeling_gpt2.py:244: TracerWarning: Converting a tensor to a Python float might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  w = w / math.sqrt(v.size(-1))
/Users/a617341/Desktop/Desktop/GPT-2/pytorch_pretrained_bert/modeling_gpt2.py:246: TracerWarning: Converting a tensor to a Python index might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  b = self.bias[:, :, ns-nd:ns, :ns]
/Users/a617341/anaconda3/lib/python3.6/site-packages/torch/onnx/utils.py:655: UserWarning: ONNX export failed on ATen operator nll_loss because torch.onnx.symbolic_opset10.nll_loss does not exist
  .format(op_name, opset_version, op_name))

KeyError: 'nll_loss'

torch.onnx.export(model, (input_ids,token_type_ids),
                "gpt2_onnx.onnx", verbose=True, input_names=['input_ids','token_type_ids'],
                          output_names=['output'], example_outputs =output, 
                  do_constant_folding=True,opset_version=10)

**Comment by prasanthpul** [comment]
Since this is specific to PyTorch, can you file this issue at https://github.com/pytorch/pytorch? @spandantiwari as fyi
