### ISSUE TITLE
Invalid padding in last AveragePooling node for inception_v1 model

### ISSUE THREAD

**Issue by LapshinA** [onnx/models#263]
Strides : 1, 1
Padding : 0, 0, 1, 1
Kernel_shape: 7, 7

If input is [1, 1024, 7, 7]
After AvgPolling - we have [1, 1024, 2, 2]
Then Reshape - [1024, 1] - It's imposibble.

In inception_v2 model version padding is correct.

**Comment by vinitra** [comment]
Hello @LapshinA. In the model you mention in the description, Inception V2, I'm seeing padding 0, 0, 0, 0, which makes sense for the reshape scenario you're referencing. [1, 1024, 7, 7] with a kernel shape of [7, 7] provides one avg pooling value for each kernel -> [1, 1024]

![image](https://user-images.githubusercontent.com/10929090/76561747-2a269b80-6461-11ea-871b-a273d0c82f19.png)

Are you referring to Inception V1?

**Comment by LapshinA** [comment]
Hello,
I mean inception v1. Link: https://s3.amazonaws.com/download.onnx/models/opset_8/inception_v1.tar.gz

**Comment by LapshinA** [comment]
inception v2 - has no problem here.

**Comment by LapshinA** [comment]
But inference of inception v1 works fine, issue can be closed.
