### ISSUE TITLE
Can't load Yolov2 onnx model on onnxruntime (0.5.0)

### ISSUE THREAD

**Issue by buttonman** [onnx/models#264]
I try to load yolov2 onnx model on onnxruntime (version:0.5.0)

following error occurs

RuntimeError: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from /Users/button/Tests/models/vision/object_detection_segmentation/yolov2/model/yolov2.onnx failed:Protobuf parsing failed.

I can load Yolov3 and tiny yolov2 without any error

only yolov2 has problem.

**Comment by leejaymin** [comment]
@buttonman yolo-v2 model could be loaded with onnxruntime 1.0 version.

**Comment by vinitra** [comment]
Recent update to the YoloV2 model in PR #269 might address the issue you're seeing as well.

**Comment by buttonman** [comment]
ok, thanks!
