### ISSUE TITLE
Inception v1 avd v2 return invalid class by comparison VGG family

### ISSUE THREAD

**Issue by LapshinA** [onnx/models#265]
I compared output inception v1 and v2 models with VGG:

D:\\vgg16.onnx - https://github.com/onnx/models/tree/master/vision/classification/vgg)
D:\\vgg19.onnx - https://github.com/onnx/models/tree/master/vision/classification/vgg
D:\\model_vgg19_8.onnx -https://s3.amazonaws.com/download.onnx/models/opset_8/vgg19.tar.gz
D:\\model18.onnx  - https://s3.amazonaws.com/download.onnx/models/opset_8/inception_v1.tar.gz   
D:\\model28.onnx  - https://s3.amazonaws.com/download.onnx/models/opset_8/inception_v2.tar.gz

**Script:**

```
import onnxruntime
import numpy as np
from PIL import Image
import matplotlib.pyplot as plt

def preprocess(input_data):
    img_data = input_data.astype('float32')
    mean_vec = np.array([0.485, 0.456, 0.406])
    stddev_vec = np.array([0.229, 0.224, 0.225])
    norm_img_data = np.zeros(img_data.shape).astype('float32')
    for i in range(img_data.shape[0]):
        norm_img_data[i, :, :] = (img_data[i, :, :] / 255 - mean_vec[i]) / stddev_vec[i]

    norm_img_data = norm_img_data.reshape(1, 3, 224, 224).astype('float32')
    return norm_img_data

test_images = ["D:\\beagle_162.jpg", "D:\\Shih-Tzu_155.jpeg", "D:\\Tiger_beetle_300.jpeg"]
models = ["D:\\vgg16.onnx", "D:\\vgg19.onnx", "D:\\model_vgg19_8.onnx", "D:\\model18.onnx", "D:\\model28.onnx"]

for image_name in test_images:
    image = Image.open(image_name)
    image = image.resize((224, 224), Image.ANTIALIAS)

    display_image = plt.imshow(image)
    plt.axis('off')
    plt.show()

    print("Image size: ", image.size)
    image_data = np.array(image).transpose(2, 0, 1)
    input_data = preprocess(image_data)
    input_data = input_data.reshape(1, 3, 224, 224)

    print('Test image name:', image_name)
    for model in models:
        session = onnxruntime.InferenceSession(model, None)
        input_name = session.get_inputs()[0].name
        result = session.run([], {input_name: input_data})
        print(' ' + model + ' predicted class:', np.argmax(result)) 

```
**Results:**
Image size:  (224, 224)
Test image name: D:\beagle_162.jpg
 D:\vgg16.onnx predicted class: 162
 D:\vgg19.onnx predicted class: 162
 D:\model_vgg19_8.onnx predicted class: 162
 D:\model18.onnx predicted class: **5**
 D:\model28.onnx predicted class: **650**

Image size:  (224, 224)
Test image name: D:\Shih-Tzu_155.jpeg
 D:\vgg16.onnx predicted class: 155
 D:\vgg19.onnx predicted class: 204
 D:\model_vgg19_8.onnx predicted class: 153
 D:\model18.onnx predicted class: **885**
 D:\model28.onnx predicted class: **650**

Image size:  (224, 224)
Test image name: D:\Tiger_beetle_300.jpeg
 D:\vgg16.onnx predicted class: 300
 D:\vgg19.onnx predicted class: 300
 D:\model_vgg19_8.onnx predicted class: 669
 D:\model18.onnx predicted class: **885**
 D:\model28.onnx predicted class: **650**

**Issues:**
For inception v1 we have two unchanged values.
For inception v2 we have three unchanged values.

**Comment by LapshinA** [comment]
![beagle_162](https://user-images.githubusercontent.com/5502685/75681930-9d801e80-5ca5-11ea-954c-864565e1d53b.jpg)
![Shih-Tzu_155](https://user-images.githubusercontent.com/5502685/75681935-9fe27880-5ca5-11ea-8075-d347c22d85ac.jpeg)
![Tiger_beetle_300](https://user-images.githubusercontent.com/5502685/75681942-a1ac3c00-5ca5-11ea-888e-adadad6230ba.jpeg)

**Comment by vinitra** [comment]
Thank you for the detailed report and the relevant replication code. It looks like the discrepancy is in preprocessing of the image data. With your code above, I am able to replicate the results you see. However, the Inception models do not require pre-processing normalization steps for the input image data. Removing normalization, I see the following results.

$ python test.py

Image size:  (224, 224)
Test image name: 162.jpg
 model18.onnx predicted class: 162
 model28.onnx predicted class: 131

Image size:  (224, 224)
Test image name: 155.jpeg
 model18.onnx predicted class: 155
 model28.onnx predicted class: 115

Image size:  (224, 224)
Test image name: 300.jpeg
 model18.onnx predicted class: 300
 model28.onnx predicted class: 620

Updated preprocess function:

```
def preprocess(input_data):
    img_data = input_data.astype('float32')
    # mean_vec = np.array([0.485, 0.456, 0.406])
    # stddev_vec = np.array([0.229, 0.224, 0.225])
    # norm_img_data = np.zeros(img_data.shape).astype('float32')
    # for i in range(img_data.shape[0]):
    #     norm_img_data[i, :, :] = (img_data[i, :, :] / 255 - mean_vec[i]) / stddev_vec[i]

    img_data = img_data.reshape(1, 3, 224, 224).astype('float32')
    return img_data
```

Looks like there is still some discrepancy for Inception v2, but Inception v1 is working as intended. We intend to add more clarity to input / output preprocessing steps in the README.

**Comment by vinitra** [comment]
Please feel free to reopen this issue if you're still having trouble!

**Comment by pjaaskel** [comment]
I can reproduce the detections for the Inception v1 ONNX model with this info, but what are the correct preprocessing steps for the Inception v2 one?
