### ISSUE TITLE
Invalid Output Name:grid

### ISSUE THREAD

**Issue by hoaquocphan** [onnx/models#268]
Hello All,

I would like to report an issue when porting tiny yolo v3 to onnxruntime.

I define the model out as below:
std::string model_out= "grid";

When the code run to below line:
CheckStatus(g_ort->Run(session, NULL, input_node_names.data(), (const OrtValue* const*)&input_tensor, 1, output_node_names.data(), 1, &output_tensor));

it appear error as below:
Invalid Output Name:grid

So there are any way to define the model out
Please help me to fix it.

Thank

**Comment by hoaquocphan** [comment]
Hi All,

Could anyone please help me.

Thanks

**Comment by hoaquocphan** [comment]
Found the root cause

**Comment by WangxingboWWW** [comment]
> Found the root cause

i have the same error, Invalid Output Name, could you tell me how to fix this ?

**Comment by praveen5733** [comment]
> > Found the root cause
> 
> i have the same error, Invalid Output Name, could you tell me how to fix this ?

Any solution for this problem?

**Comment by jpower10** [comment]
I fixed it by observing the output name of the model. I changed "output" on line 164 to "softmax".
![image](https://github.com/onnx/models/assets/65607280/ba67ac6a-1cef-4f9f-9901-a3f2f2c6f57d)
