### ISSUE TITLE
Migrate all models to Git LFS, deprecate individual links

### ISSUE THREAD

**Issue by vinitra** [onnx/models#271]
For onnx models in the model zoo that are currently represented by download links, add git LFS representations.

Instructions:
 

-  [Example PR for Git LFS Migration (Emotion FER+)](https://github.com/onnx/models/pull/278)
-  Navigate to github page and download model from links on github page
-  Create a model folder (for the .onnx files, the .tar.gz files)
        - If there are only .tar.gz files, and not .onnx files, make sure to extract .onnx files from the tar.gz and update the README
         - Naming conventions can be found in the sample PR (i.e. bert-squad-8.onnx and bert-squad-8.tar.gz)
- If there are other relevant files already in the folder, create a "dependencies" folder and move those scripts there -- see BERT for example.
- To use LFS, Simply git commit / push with the files in the correct locations
- Remember to use relative file links in the README

cc: @prasanthpul, @KsenijaS, @rajeevsrao

**Comment by ChiaraXian** [comment]
Sorry to bother you. I tried command git lfs pull --include="*" --exclude="" to download all onnx models. However, I couldn't find any onnx classification model. So I only could get onnx classification models from download links?

Thank you for your help!

**Comment by vinitra** [comment]
Hi @ChiaraXian -- this migration to LFS is currently in progress and has not yet been fully completed. Therefore, only the subset of models which have already been moved to LFS will be available with the following command. For now, please use the download links!

**Comment by vinitra** [comment]
Text models complete, working on vision models.
