### ISSUE TITLE
Does onnx conversion has support for any kind of models? Only Deep Learning models or Machine Learning models too?

### ISSUE THREAD

**Issue by Dhanashri-Dhanashri** [onnx/models#277]
In the model zoo, Ive found only those models that takes input an image. So my question is, is there support for models that takes numerical data as input?

**Comment by vinitra** [comment]
Hi @Dhanashri-Dhanashri! We support all kinds of models, from those with image input data, to text input data, to numerical input data. ONNX supports both [traditional machine learning](https://github.com/onnx/onnx/blob/master/docs/Operators-ml.md) and [deep learning](https://github.com/onnx/onnx/blob/master/docs/Operators.md) operators.

We unfortunately do not have many offerings with numerical input in the Model Zoo, but we welcome contributions.
