### ISSUE TITLE
Yolov2-COCO

### ISSUE THREAD

**Issue by davdu31** [onnx/models#285]
Hello,

When I run [Yolov2-Coco](https://github.com/onnx/models/tree/master/vision/object_detection_segmentation/yolov2-coco) model in C# with ML.net I get unlikely results. I use the same [algorithm](https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/end-to-end-apps/ObjectDetection-Onnx) for Yolov2 and Yolov2-Coco and with Yolov2 the results are great. Why the boxes and labels are inconsistent with Yolov2-coco ?

Thanks

**Comment by vinitra** [comment]
https://github.com/onnx/models/pull/274

@leejaymin
