### ISSUE TITLE
How to get objects scores from output in Yolov3

### ISSUE THREAD

**Issue by hoaquocphan** [onnx/models#291]
Hi All,

I'm porting [Yolo v3](https://github.com/onnx/models/tree/master/vision/object_detection_segmentation/tiny_yolov3) on [onnxruntime ](https://github.com/microsoft/onnxruntime/tree/rel-1.0.0) by C code.

The model run successfully and have 3 output as defined in  [Yolo v3](https://github.com/onnx/models/tree/master/vision/object_detection_segmentation/tiny_yolov3) 
[boxes:](https://github.com/hoaquocphan/Tiny_Yolo_v3/blob/master/boxes.txt)
```
-101.76323699951172
-12.98329353332520
.
.
.
216.74037170410156
1.44414448738098
```

[scores:](https://github.com/hoaquocphan/Tiny_Yolo_v3/blob/master/scores.txt)
```
-0.00000000298391
-0.00000000769582
.
.
.
-0.00000000405639
0.00000001776875
```
[indices:](https://github.com/hoaquocphan/Tiny_Yolo_v3/blob/master/indices.txt)
```
0
1
251
0
7
108
0
16
319
```
With the [indices:](https://github.com/hoaquocphan/Tiny_Yolo_v3/blob/master/indices.txt), I can detect the bicycle, truck, dog, as below:

```
Result 1
Detected        : bicycle
Bounding Box    : (X, Y, W, H) = (169.03, 203.06, 340.61, 235.45)
Score           : 

Result 2
Detected        : truck
Bounding Box    : (X, Y, W, H) = (332.86, 92.03, 142.98, 61.44)
Score           : 

Result 3
Detected        : dog
Bounding Box    : (X, Y, W, H) = (76.96, 277.38, 128.82, 226.34)
Score           : 
```

but I don't know how to get the objects score of bounding box as the guide in  [Yolo v3](https://github.com/onnx/models/tree/master/vision/object_detection_segmentation/tiny_yolov3), the guide is too simple. 
So could anyone help me about this?

Thanks

**Comment by hoaquocphan** [comment]
complete by myself

**Comment by MuhammadAsadJaved** [comment]
@hoaquocphan   I also do not understand the Yolov3 example for the interface. Can you share the complete code that I can use to import the .onnx model and do interface on the input image?   

Thanks

**Comment by hoaquocphan** [comment]
Hi @MuhammadAsadJaved,
my code here [Yolo_v3.cpp](https://github.com/hoaquocphan/Yolo_v3/blob/master/Yolo_v3.cpp)

**Comment by MuhammadAsadJaved** [comment]
> Hi @MuhammadAsadJaved,
> my code here [Yolo_v3.cpp](https://github.com/hoaquocphan/Yolo_v3/blob/master/Yolo_v3.cpp)

Hi, seems like you used this code for another project. Is there any python example?  Or How I can run your code in Ubuntu? As you have some compilation conditions.

**Comment by hoaquocphan** [comment]
My preprocessing and postprocessing steps are detail in Yolo_v3.cpp. 
so you can refer to it and write a new python code to run on ubuntu, it is very easy.

**Comment by MuhammadAsadJaved** [comment]
OK. Thanks

**Comment by MuhammadAsadJaved** [comment]
@hoaquocphan  With the [Yolov3 example](https://github.com/onnx/models/tree/master/vision/object_detection_segmentation/yolov3), I am able to run my model and  I have printed the  `out_classes, out_scores, out_boxes` and got the following output. The first row is classes, the second row is scores and next rows are bbox coordinates.  but the bbox coordinates doesn't look right. does it need any post-processing to get the exact bounding box values or this one is final bbox coordinate values??  

Output
```
[1, 7, 16]
[0.9877432, 0.8937931, 0.9979729]
[array([ 87.74066,  84.49133, 311.78384, 307.02115], dtype=float32), array([ 59.89547, 258.38895, 121.89446, 374.37015], dtype=float32), array([164.15099,  65.86013, 386.56052, 175.9433 ], dtype=float32)]
```

**Comment by hoaquocphan** [comment]
the output from model is ymin, xmin,  ymax, xmax.
base on your requirement, so you should calculate the coordinate of bb box base on above output

my source code have detail about that:
```
            float ymin = out1[out3[i+2]*4];
            float xmin = out1[out3[i+2]*4+1];
            float ymax = out1[out3[i+2]*4+2];
            float xmax = out1[out3[i+2]*4+3];
            Box bb = float_to_box((xmin+xmax)/2, (ymin+ymax)/2, xmax-xmin, ymax-ymin);
```

**Comment by MuhammadAsadJaved** [comment]
> the output from model is ymin, xmin, ymax, xmax.
> base on your requirement, so you should calculate the coordinate of bb box base on above output
> 
> my source code have detail about that:
> 
> ```
>             float ymin = out1[out3[i+2]*4];
>             float xmin = out1[out3[i+2]*4+1];
>             float ymax = out1[out3[i+2]*4+2];
>             float xmax = out1[out3[i+2]*4+3];
>             Box bb = float_to_box((xmin+xmax)/2, (ymin+ymax)/2, xmax-xmin, ymax-ymin);
> ```

Thank you so much.

**Comment by rohitdavas** [comment]
Is it sure that the output from the onnx models are of the format y_min, x_min, y_max, x_max ? if so, if am not seeing the case.

![Image](https://github.com/user-attachments/assets/87d3df40-90d0-4bfb-b723-36fbf9eb42ad)
