### ISSUE TITLE
How to export ONNX model by torch with node name ?

### ISSUE THREAD

**Issue by wang-y-z** [onnx/models#305]
[this models have node name](https://github.com/onnx/models/tree/master/vision/classification/shufflenet/model)
![image](https://user-images.githubusercontent.com/57429717/81903905-13352e80-95f5-11ea-943f-47d56afe197a.png)
but when I export ONNX with pytorch1.0/1.2/1.4, it seems that I can't set the node name by myself
![image](https://user-images.githubusercontent.com/57429717/81904041-4677bd80-95f5-11ea-9c11-1ae60fe5cf4a.png)

by the way: I want to set node name not the inputs name list, thanks a lot !

**Comment by vinitra** [comment]
Using Netron, the node name is only displayed when it is included in the model graph. You can use the [ONNX Python IR](https://github.com/onnx/onnx/blob/master/docs/IR.md#nodes) to modify the nodes and add node names manually. 

```
>>> import onnx
>>> model = onnx.load('resnet101-v1-7.onnx')
>>> nodes = model.graph.node
>>> nodes[0]
input: "data"
input: "resnetv18_conv0_weight"
output: "resnetv18_conv0_fwd"
name: "resnetv18_conv0_fwd"
op_type: "Conv"
attribute {
  name: "dilations"
  ints: 1
  ints: 1
  type: INTS
}
attribute {
  name: "group"
  i: 1
  type: INT
}
attribute {
  name: "kernel_shape"
  ints: 7
  ints: 7
  type: INTS
}
attribute {
  name: "pads"
  ints: 3
  ints: 3
  ints: 3
  ints: 3
  type: INTS
}
attribute {
  name: "strides"
  ints: 2
  ints: 2
  type: INTS
}
>>> nodes[0].name = 'node_name'
```

Alternatively, you can submit an issue / feature request to the [PyTorch-ONNX exporter](https://github.com/pytorch/pytorch/tree/master/torch/onnx) in the PyTorch repository.

**Comment by wang-y-z** [comment]
Thanks for your precise solution for this issue~ it really worked
