### ISSUE TITLE
Cannot run bertsquad-10.onnx on Ubuntu

### ISSUE THREAD

**Issue by lifuhuang** [onnx/models#306]
Running BERT-Squad.ipynb failed when loading onnx file.

Dependency versions:
onnxruntime-1.2.0
onnx-1.7.0
python 3.7.5
libprotoc-dev: 3.0.0-9.1ubuntu1
protobuf-compiler: 3.0.0-9.1ubuntu1

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-4-a43b1aa6e60c> in <module>
      1 # run inference
      2 
----> 3 session = ort.InferenceSession('bertsquad-10.onnx')
      4 
      5 for input_meta in session.get_inputs():

~/.local/lib/python3.7/site-packages/onnxruntime/capi/session.py in __init__(self, path_or_bytes, sess_options, providers)
     23         self._path_or_bytes = path_or_bytes
     24         self._sess_options = sess_options
---> 25         self._load_model(providers)
     26         self._enable_fallback = True
     27 

~/.local/lib/python3.7/site-packages/onnxruntime/capi/session.py in _load_model(self, providers)
     30             self._sess = C.InferenceSession(
     31                 self._sess_options if self._sess_options else C.get_default_session_options(),
---> 32                 self._path_or_bytes, True)
     33         elif isinstance(self._path_or_bytes, bytes):
     34             self._sess = C.InferenceSession(

RuntimeError: /onnxruntime_src/onnxruntime/core/session/inference_session.cc:215 onnxruntime::InferenceSession::InferenceSession(const onnxruntime::SessionOptions&, const string&, onnxruntime::logging::LoggingManager*) status.IsOK() was false. Given model could not be parsed while creating inference session. Error message: Protobuf parsing failed.

**Comment by ChenBoSyun** [comment]
Hi , I have the same problem.
Can you tell me how you solved it , thanks.

**Comment by lifuhuang** [comment]
@ChenBoSyun , for my case, it was because Git did not download the whole onnx file. A corrupted one was parsed by the Protobuf thus the failure.
