### ISSUE TITLE
No PB format test data for resnet50 and shufflenet?

### ISSUE THREAD

**Issue by snnn** [onnx/models#31]
There are only some npz files.

**Comment by houseroad** [comment]
I am working on polishing the test data for these models. :-)

**Comment by houseroad** [comment]
I have uploaded new model files. 

https://s3.amazonaws.com/download.onnx/models/opset_6/resnet50.tar.gz

Let me know if anything else is missing.

**Comment by snnn** [comment]
Great! I've tested it. It's perfect!

Thank you
