### ISSUE TITLE
Shape Discrepancy in Super Resolution Model

### ISSUE THREAD

**Issue by agnesnatasya** [onnx/models#311]
The super resolution model, https://github.com/onnx/models/tree/master/vision/super_resolution/sub_pixel_cnn_2016, has 672 x 672 data, but the raw data stated that the dimension is 224 x 224 instead. This causes error if the user does some validation during loading the dataset. 

Please help revise. Thank you.

**Comment by vinitra** [comment]
The input to the model is 224 x 224, as indicated in the image below. The output of the model is 672 x 672. If you have an image input that has the same dimensions for width and height (a square image), you can resize it into appropriate model input using the [preprocessing code in the model README](https://github.com/onnx/models/tree/master/vision/super_resolution/sub_pixel_cnn_2016#preprocessing). 

![image](https://user-images.githubusercontent.com/10929090/83465136-c55b5b80-a427-11ea-873f-408728c8f393.png)

Feel free to reopen this issue if you have further questions!
