### ISSUE TITLE
FER+ Emotion Recognition - Dataset / input

### ISSUE THREAD

**Issue by M-Tonin** [onnx/models#314]
Dears,

It is a simple question where I can found de dataset with image (1x64x64), the dataset link is not Available (https://www.kaggle.com/c/challenges-in-representation-learning-facial-expression-recognition-challenge/data) and the description is about 48x48 (not 64x64).

Thanks;

**Comment by ebarsoum** [comment]
Here the original code for training: https://github.com/Microsoft/FERPlus
The data was resized during preprocessing.
