### ISSUE TITLE
MNIST opset 1 is missing opset_import IR component

### ISSUE THREAD

**Issue by vinitra** [onnx/models#320]
Seeing this issue upon loading MNIST opset 1. Looks like a missing opset_import attribute at the ModelProto level.

``Failed to load model with error: Missing opset in the model. All ModelProtos MUST have at least one entry that specifies which version of the ONNX OperatorSet is being imported.``

**Comment by snnn** [comment]
I have a new mnist model that converted from tensorflow, with same functionality but bigger model size(6.3MB vs 26KB). And I believe it will solve the issue and supports more opsets because TF converter is actively maintained, but CNTK is dead. If you wants the new model, please let me know.
