### ISSUE TITLE
Super resolution bug in output data

### ISSUE THREAD

**Issue by alrevuelta** [onnx/models#321]
# Bug Report

### Which model does this pertain to?
This bug report belongs to the [super_resolution](https://github.com/onnx/models/tree/master/vision/super_resolution/sub_pixel_cnn_2016) model.

### Describe the bug
When reading the `output_0.pb` and trying to parse the `raw_data` I'm getting an error, because it contains 451584 elements (672x672 image) but its dimensions are 224x224.

### Reproduction instructions

**System Information**  

OS Platform and Distribution (*e.g. Linux Ubuntu 16.04*): macOS 19.13.6
ONNX version (*e.g. 1.6*): 1.7.0
Backend/Runtime version (*e.g. ONNX Runtime 1.1, PyTorch 1.2*):  NA

The error can be reproduced with:
```python
import onnx
tensor = onnx.load_tensor("test/super_resolution/test_data_set_0/output_0.pb")
np_array = numpy_helper.to_array(tensor)
```

Error: `ValueError: cannot reshape array of size 451584 into shape (224,224)`

This error of course makes sense because.
```python
print(tensor.dims) # [224, 224] but should be [672, 672]
print(len(tensor.raw_data)) #1806336 divided by 4 (bytes per float), thats 451584 (672x672)
```

So according to this I would say that `output_0.pb` outputs are wrong. I guess these files are autogenerated, so maybe there are other problems somewhere else?

**Edit**: Actually the output should be 1x1x672x672 to be consistent with the model.

### Notes
NA

**Comment by alrevuelta** [comment]
Anyone?

**Comment by vinitra** [comment]
@alrevuelta Thanks for letting us know with a detailed bug report and replication steps! I can confirm that I'm seeing the same error you're seeing with output_0.pb and will generate new sample data accordingly.
