### ISSUE TITLE
shufflenet test data seems to be mistaken

### ISSUE THREAD

**Issue by nihui** [onnx/models#33]
hello

recently, I've been playing onnx models with ncnn converter.
I found that all the models in this repo can be processed using the bundled test data without errors, except the shufflenet model, which always produces different result with the desired test output.

And, I found that the three test data in shufflenet model archive are identical with each other.

test_data_0.npy
test_data_1.npy
test_data_2.npy

Is there anything wrong with the test data ?

**Comment by spandantiwari** [comment]
Also, some of the BatchNormalization ops in this model have the consumed_inputs attribute, which has been removed from the current version. (https://github.com/onnx/models/issues/35, https://github.com/onnx/models/issues/13)

**Comment by vinitra** [comment]
Please see the recent updates with ShuffleNet v2 here: https://github.com/onnx/models/tree/master/vision/classification/shufflenet
