### ISSUE TITLE
yolo v4 post process missing

### ISSUE THREAD

**Issue by photoszzt** [onnx/models#330]
# Bug Report

### Which model does this pertain to?
Mention the relevant onnx models from the model zoo here.
yolo v4
### Describe the bug

I follow the instruction on post processing, but I get this:
Traceback (most recent call last):
  File "inference.py", line 56, in <module>
    pred_bbox = utils.postprocess_bbbox(np.expand_dims(detections, axis=0), ANCHORS, STRIDES, XYSCALE)
AttributeError: module 'core.utils' has no attribute 'postprocess_bbbox'

### Reproduction instructions

**System Information**  

OS Platform and Distribution (*e.g. Linux Ubuntu 16.04*):  Linux Ubuntu 18.04
ONNX version (*e.g. 1.6*):  1.6
Backend/Runtime version (*e.g. ONNX Runtime 1.1, PyTorch 1.2*):  ONNX Runtime

Provide a code snippet to reproduce your errors.
```
from core.config import cfg
import core.utils as utils
from PIL import Image

ANCHORS = utils.get_anchors(cfg.YOLO.ANCHORS)
STRIDES = np.array(cfg.YOLO.STRIDES)
XYSCALE = cfg.YOLO.XYSCALE

pred_bbox = utils.postprocess_bbbox(np.expand_dims(detections, axis=0), ANCHORS, STRIDES, XYSCALE)
...
```

### Notes
Any additional information

**Comment by askhade** [comment]
@jennifererwangg  : Your inference jupyter notebook takes a dependency on "https://github.com/hunglc007/tensorflow-yolov4-tflite/blob/master/core/utils.py" which was recently changed. Can you add a fix.

@vinitra : What is the general practice here? How can we avoid taking such dependencies. This is a maintenance issue.

**Comment by photoszzt** [comment]
It would be great if the notebook contains the actual source code rather than the reference. The original author has the freedom to change their code at any time.

**Comment by mustafakasap** [comment]
Post process function in the original source code is using 
      import tensorflow as tf
for just post processing the onnx.run result. Better to re-write the post-process function with core python libs or in onnx.
Main issue for me is to not to increase my container size by installing both Tensorflow libraries and Onnx runtime together.

**Comment by vinitra** [comment]
Thanks for the feedback, all! Following up with @jennifererwangg to update this.

**Comment by cardboardcode** [comment]
@photoszzt 

# [Cause of Issue]
This issue is caused by the fact that functions **postprocess_bbbox** and **postprocess_box** were removed from the `utils.py` file under in [commit 9ab36aaa90c46aa063e3356d8e7f0e5bb27d919b](https://github.com/hunglc007/tensorflow-yolov4-tflite/commit/9ab36aaa90c46aa063e3356d8e7f0e5bb27d919b) of **[tensorflow-yolov4-tflite](https://github.com/hunglc007/tensorflow-yolov4-tflite)**.

**Comment by mustafakasap** [comment]
still minor bugs exist:
fixed are in https://github.com/onnx/models/pull/349


> Line 78 changed from import scipy to  **from scipy import special** Before "special" was not imported by default
> 
> Line 216 changed from
>      def draw_bbox(image, bboxes, classes=read_class_names(cfg.YOLO.CLASSES), show_label=True):
> to 
>      def draw_bbox(image, bboxes, classes=read_class_names("coco.names"), show_label=True):
> as label names are not stored in cfg object as in tensorflow or darknet original samples.
