### ISSUE TITLE
EfficientNet-Lite4 sample data missing

### ISSUE THREAD

**Issue by pbert519** [onnx/models#335]
# Bug Report

### Which model does this pertain to?
EfficientNet-Lite4

### Describe the bug
The 'Download (with sample test data)' link results in a 404 error page.  

### Reproduction instructions
goto https://github.com/onnx/models/tree/master/vision/classification/efficientnet-lite4 and click on Download (with sample test data)

### Notes
There is a file under vision/classification/efficientnet-lite4model/ with the same name as the file in the download link, but the tar archive does not contain any sample data.

**Comment by vinitra** [comment]
Thanks for the report! @shirleysu8, can you address this in #336 as well?
