### ISSUE TITLE
Format of input and output Tensors

### ISSUE THREAD

**Issue by newling** [onnx/models#34]
Certain model files contain npz inputs and outputs but no serialized protobuf TensorProtos. 

The latter format is useful for Pythonless workflows. Would be good if either (i) all files contain protobuf files or (ii) a script for converting npz -> protobuf files is provided.

**Comment by newling** [comment]
Found the functionality I seem to need to make the conversion:
```
tensor = numpy_helper.from_array(numpy_array)
print('TensorProto:\n{}'.format(tensor))
```
But it'd still be good to have the .pb files in model directories.

**Comment by snnn** [comment]
Only 3 of them don't have pb data files.

MNIST/Emotion/Tinyyolo

**Comment by newling** [comment]
Ok, not many. But thought I'd just let you know that having them in TensorProto format is useful.

**Comment by mx-iao** [comment]
@newling We are going to add pb files for the rest of the models

**Comment by mx-iao** [comment]
added .pb files for MNIST/Emotion/Tinyyolo
