### ISSUE TITLE
Unable to use yolov4: INVALID_GRAPH

### ISSUE THREAD

**Issue by cardboardcode** [onnx/models#342]
# Bug Report

### Which model does this pertain to?
**yolov4** [[link]](https://github.com/onnx/models/tree/master/vision/object_detection_segmentation/yolov4)

### Describe the bug
Unable to instantiate **yolov4** model as onnxruntime session. 

Upon running the minimal code example in the Reproduction instructions, the following error is encountered.

```txt
RuntimeError: [ONNXRuntimeError] : 10 : INVALID_GRAPH : Load model from yolov4.onnx failed:Node:Resize__697 Node 
(Resize__697) has input size 4 not in range [min=2, max=2].
```

### Reproduction instructions

**System Information**  

OS Platform and Distribution (*e.g. Linux Ubuntu 16.04*):  **Ubuntu 18.04**
ONNX version (*e.g. 1.6*):  **1.7** (Also attempted **1.6** as well)
Backend/Runtime version (*e.g. ONNX Runtime 1.1, PyTorch 1.2*):  **onnxruntime 1.3.0**

Provide a code snippet to reproduce your errors.
```
import onnxruntime as rt
sess = rt.InferenceSession("yolov4.onnx")
```

### Notes
Any constructive help is appreciated. Thank you. Feel free to ask for more details.

**Comment by skottmckay** [comment]
The Resize operator changed in opset 11 to take 3 or 4 inputs (previously took 2). The model is opset 11, and the Resize node has a valid number of inputs given that. 

Based on the error message it seems like you're potentially running an old version of onnxruntime which is only aware of opset 10 or earlier and is expecting only 2 inputs for the Resize. Can you please check the version? `help(rt)` in python should include help text with the version number in it.

I'm able to successfully load the model with onnxruntime v1.3.0.

**Comment by cardboardcode** [comment]
Thanks for the quick clarification. 

Will give a try once I get the time. Will update here with the result.s

**Comment by cardboardcode** [comment]
# Verified to no longer face this issue. 

Current virtual python environment that works with the code snippet above.

```txt
# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: linux-64
@EXPLICIT
https://repo.anaconda.com/pkgs/main/linux-64/_libgcc_mutex-0.1-main.conda
https://repo.anaconda.com/pkgs/main/linux-64/ca-certificates-2020.6.24-0.conda
https://repo.anaconda.com/pkgs/main/linux-64/ld_impl_linux-64-2.33.1-h53a641e_7.conda
https://repo.anaconda.com/pkgs/main/linux-64/libstdcxx-ng-9.1.0-hdf63c60_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libgcc-ng-9.1.0-hdf63c60_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libffi-3.3-he6710b0_2.conda
https://repo.anaconda.com/pkgs/main/linux-64/ncurses-6.2-he6710b0_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/openssl-1.1.1g-h7b6447c_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/xz-5.2.5-h7b6447c_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/zlib-1.2.11-h7b6447c_3.conda
https://repo.anaconda.com/pkgs/main/linux-64/libedit-3.1.20191231-h14c3975_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/readline-8.0-h7b6447c_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/tk-8.6.10-hbc83047_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/sqlite-3.32.3-h62c20be_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/python-3.6.10-h7579374_2.conda
https://repo.anaconda.com/pkgs/main/linux-64/certifi-2020.6.20-py36_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/setuptools-49.2.0-py36_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/wheel-0.34.2-py36_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pip-20.1.1-py36_1.conda
```
# [Solution]
1. **Save** the code above to a `conda_env.txt` file. 
2. **Create** the python virtual environment using the command below:
```bash
 conda create --name onnx_cpu --file conda_env.txt
```

**Comment by cardboardcode** [comment]
However, in trying to use **yolov4.onnx**, now facing another issue as highlighted in detail in issue #330.
