### ISSUE TITLE
Yolo v2 model contains a deprecated ImageScalar operator

### ISSUE THREAD

**Issue by sfatimar** [onnx/models#344]
Yolo v2 model contains a deprecated operator. Image Scalar which does not run with openvino ep. 

### Which model does this pertain to?
Yolo v2

### Describe the bug
https://github.com/onnx/models/issues/76 this issue was also with tiny yolo v2 and fixed there in opset version 8 but not in yolo v2. ImageScaler was an experimental ops and not supported anymore

### Reproduction instructions
Run it on onnxruntime with openvino execution provider 

**System Information**  
 Linux Ubuntu 18.04:  
Onnxruntime.

**Comment by skottmckay** [comment]
@jiafatom are you able to update the yolo v2 model in the same way you updated the tiny yolo v2 model?

**Comment by jiafatom** [comment]
@sfatimar this yolov2 model is converted from a coreml model. This coreml2onnx converter is not actively developing. Since yolov2 is outdated, the easiest way is that: can you use yolov3 model instead?

**Comment by sfatimar** [comment]
alright i guess
