### ISSUE TITLE
A bug in the model RoBERTa

### ISSUE THREAD

**Issue by joddiy** [onnx/models#351]
# Bug Report

### Which model does this pertain to?
Text model, [RoBERTa](https://github.com/onnx/models/tree/master/text/machine_comprehension/roberta)

### Describe the bug
I try to run this model in the onnx runtime, it reports the following error:

>6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Expand node. Name:'' Status Message: /Users/runner/work/1/s/onnxruntime/core/providers/cpu/math/element_wise_ops.h:361 void onnxruntime::BroadcastIterator::Init(int64_t, int64_t) axis == 1 || axis == largest was false. Attempting to broadcast an axis by a dimension other than 1. 7 by 13

It seems in the model, for the expand operator in the following picture, it has an input with shape 1\*13, but the new_shape of the operator comes from the input text sequence, its shape is 1\*7 for the input "This film is so good". The 1\*13 input cannot expand to the new_shape of 1\*7.

![image](https://user-images.githubusercontent.com/14108933/89539856-ddd46180-d82e-11ea-98d3-36a6dd2d9a7d.png)

### Reproduction instructions

**System Information**  

OS Platform and Distribution (*e.g. Linux Ubuntu 16.04*):  MacOS 10.15.6
ONNX version (*e.g. 1.6*):  1.6
Backend/Runtime version (*e.g. ONNX Runtime 1.1, PyTorch 1.2*):  ONNX Runtime 1.4.0

Provide a code snippet to reproduce your errors.
Just run the demo code in https://github.com/onnx/models/blob/master/text/machine_comprehension/roberta/dependencies/roberta-sequence-classification-inference.ipynb

### Notes
Any additional information

**Comment by joddiy** [comment]
@kundanapillari Hi, thanks for your contribution to this model. and can you help to check it?

**Comment by kundanapillari** [comment]
Created https://github.com/onnx/models/pull/352 to fix the issue.

**Comment by vinitra** [comment]
Closed with #352
