### ISSUE TITLE
How can I convert pytorch pretrained bert model to onnx model

### ISSUE THREAD

**Issue by KellyZhang2020** [onnx/models#361]
When I convert the pytorch pretrained bert model to onnx model  as follows:

```
import os
import torch
from pytorch_pretrained_bert import BertTokenizer, BertModel

model = BertModel.from_pretrained('bert-base-uncased')

input_1 = torch.LongTensor(1, 14)
input_2 = torch.LongTensor(1, 14)
input_3 = torch.LongTensor(1, 14)
base_path = os.path.dirname(__file__)
onnx_path = os.path.join(base_path, 'bert.onnx')
torch.onnx.export(model, (input_1, input_2, input_3), onnx_path)
```
**raise error**: 
`IndexError: index out of range in self`
     
- `transformers` version: 3.0.2
- Platform: pycharm
- Python version: 3.8
- PyTorch version (GPU?): 1.6.0 no GPU
- onnx version: 1.7.0
- pytorch-pretrained-bert version: 0.6.2

How can I convert pytorch pretrained bert model to onnx model？ Thank you for the help :)

**Comment by skaarthik** [comment]
@KellyZhang2020 try following the sample at https://github.com/huggingface/transformers/blob/master/notebooks/04-onnx-export.ipynb. More details at https://medium.com/microsoftazure/accelerate-your-nlp-pipelines-using-hugging-face-transformers-and-onnx-runtime-2443578f4333.

**Comment by lukesalamone** [comment]
For posterity: the notebook link has changed to https://github.com/huggingface/notebooks/blob/main/examples/onnx-export.ipynb

**Comment by leiqing110** [comment]
I have the same problem, have you solved it?
