### ISSUE TITLE
GPT 2 model loading

### ISSUE THREAD

**Issue by C00reNUT** [onnx/models#369]
# Ask a Question

### Question
Hello, I am trying to implement text generation using gpt 2 and onnx. Acording to the example provided in https://github.com/onnx/models/tree/master/text/machine_comprehension/gpt-2 I tried to run the code (see below).  

I end up with TypeError: 'ModelProto' object is not callable. 

**What is the correct way to load/initialize the model?**

Is this issue related to a specific model?  
**Model name** (*e.g. mnist*):  gpt 2
**Model opset** (*e.g. 7*):  10

### Notes
```
import numpy as np
import torch
import onnx
import torch.nn.functional as F
from transformers import GPT2Tokenizer

model = onnx.load('gpt2-lm-head-10.onnx')

batch_size = 1
length = 10
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
tokenizer = GPT2Tokenizer.from_pretrained('gpt2')

text = "Here is some text to encode : Hello World!"
tokens = np.array(tokenizer.encode(text))
context = torch.tensor(tokens, device=device, dtype=torch.long).unsqueeze(0).repeat(batch_size, 1)
prev = context
output = context

for i in range(length):
    outputs = model(prev)
    logits = outputs[0]
    logits = logits[:, -1, :]
    log_probs = F.softmax(logits, dim=-1)
    _, prev = torch.topk(log_probs, k=1, dim=-1)
    output = torch.cat((output, prev), dim=1)

output = output[:, len(tokens):].tolist()
generated = 0
for i in range(batch_size):
    generated += 1
    text = tokenizer.decode(output[i])
    print(text)
```

**Comment by tianleiwu** [comment]
You will need a runtime (For example ONNX Runtime) that can use onnx model to run inference.

Here is a notebook for GPT-2 in ONNX runtime:
https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/python/tools/transformers/notebooks/Inference_GPT2_with_OnnxRuntime_on_CPU.ipynb

**Comment by C00reNUT** [comment]
@tianleiwu thank you!
