### ISSUE TITLE
Question in loading model yolov4 ? 

### ISSUE THREAD

**Issue by hoangkhoiLE** [onnx/models#395]
# Ask a Question

### Question
I got a problem when i tried to load the model "yolov4.onnx" provided by @jennifererwangg in the link https://github.com/onnx/models/tree/master/vision/object_detection_segmentation/yolov4/model
![image](https://user-images.githubusercontent.com/57557628/98240044-248a4280-1f69-11eb-9ffa-dfc99898a29f.png)

### Further information
I have tried to convert a new model yolov4 from tutorial 

https://github.com/jennifererwangg/models/blob/jennifer-yolov4/vision/object_detection_segmentation/yolov4/dependencies/Conversion.ipynb  provided by @jennifererwangg

But when i checked model onnx from this tutorial https://github.com/jennifererwangg/models/blob/jennifer-yolov4/vision/object_detection_segmentation/yolov4/dependencies/onnx-model-validation.ipynb  provided by @jennifererwangg

I see that there a different between the result in the notebook and mine. Particularly in the output:

In the notebook original:
![image](https://user-images.githubusercontent.com/57557628/98240430-aed2a680-1f69-11eb-87ec-b3743268f107.png)

In my notebook 
![image](https://user-images.githubusercontent.com/57557628/98240505-cd38a200-1f69-11eb-96e2-4c29085464e1.png)

I have even tried in some machine and env-python different but the results is still liked in my notebook. So the output of model is not compatible with the way we do inference in 
https://github.com/jennifererwangg/models/blob/jennifer-yolov4/vision/object_detection_segmentation/yolov4/dependencies/inference.ipynb

Please help me to identify the problem.

Best regard

Is this issue related to a specific model?  
**Model name** (*e.g. mnist*):  yolov4
**Model opset** (*e.g. 7*): 11

### Notes
Any additional information, code snippets.

**Comment by bedilbek** [comment]
Hey @hoangkhoiLE. Did you resolve this issue?

**Comment by bedilbek** [comment]
The workaround is [here](https://github.com/onnx/models/issues/390#issuecomment-779605484)

**Comment by hoangkhoiLE** [comment]
@bedilbek  sorry for late response, I just redownload a file and it works, like you see in #390
