### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'run'

### ISSUE THREAD

**Issue by ggjjj** [onnx/models#4]
I got this sample code from https://github.com/onnx/models  and wanted to see it running with ONNX model. I took resnet50 as example and the following error.

import numpy as np
import onnx
import caffe2
from onnx.backend.base import Backend

model_path = '/home/onnx/Downloads/resnet50/model.pb'
npz_path = '/home/onnx/Downloads/resnet50/test_data_0.npz'
model = onnx.load(model_path)
sample = np.load(npz_path, encoding='bytes')

inputs = list(sample['inputs'])
outputs = list(sample['outputs'])
np.testing.assert_almost_equal(outputs, Backend.run_model(model, inputs))

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-11-7ce47abfb55e> in <module>()
     12 outputs = list(sample['outputs'])
     13 
---> **14 np.testing.assert_almost_equal(outputs,Backend.run_model(model, inputs))**

/anaconda/lib/python2.7/site-packages/onnx/backend/base.pyc in run_model(cls, model, inputs, device, **kwargs)
     55     @classmethod
     56     def run_model(cls, model, inputs, device='CPU', **kwargs):
---> 57         cls.prepare(model, device, **kwargs).run(inputs)
     58 
     59     @classmethod

**AttributeError: 'NoneType' object has no attribute 'run'**

Let me know how to overcome this error? Why is it returning 'NoneType'

**Comment by bddppq** [comment]
This is a known bug that has been fixed recently 805a96. Please clone the onnx source code from github and install from it.

**Comment by gjeganmo** [comment]
Question 1: Can ONNX by itself run models without caffe2/pytorch? If yes how?
Question 2: What version/tag of Pytorch or Caffe2 will work with onnx/onnx@805a96a?

**Comment by houseroad** [comment]
Q2: Our run_model function design is pretty stable. It should work with the current master branch of pytorch and caffe2. Please let me know if you have any question about it.

**Comment by shbnm21** [comment]
I am getting error on running function
np.testing.assert_almost_equal(torch_out.data.cpu().numpy(), c2_out, decimal=3)

Error is
Attribute Error :'Nonetype' object has no attribute'data'

Please help to resolve this error
