### ISSUE TITLE
Script won't work for existing models when multiple outputs have empty string as name

### ISSUE THREAD

**Issue by chinhuang007** [onnx/models#403]
The CI model test script assumes that model outputs have unique names. That is not the case currently with some models, including MaskRCNN-10, FasterRCNN-10, and maybe others. The output pbs all have empty string "" as the output name. The script below will override the dictionary entry and end up with only one output. The check will fail later because the mismatch of number of outputs.

https://github.com/onnx/models/blob/953e2608b2a00b809cd2df86520aa9620c1b0463/workflow_scripts/ort_test_dir_utils.py#L170

There are two possible solutions: 1. enforce all model output pbs to include unique output names 2. change the script to use output file name such as "output_0.pb"  to match up with output name in the model itself sequentially when name is empty string

**Comment by wenbingl** [comment]
adding @jcwchen for more comments.

**Comment by jcwchen** [comment]
Hi @chinhuang007,
Actually there is no test_data_set_0 in onnx/models for MaskRCNN-10 and FasterRCNN-10. And output_X.pb can be produced correctly by ort_test_dir_utils.py... Do you produce these outputs by other method?

IMO, 1 is more ideal.

**Comment by jcwchen** [comment]
Sorry I got what you meant and I did see those broken output .pb files in onnx/models... If we do 1), it seems that there are some input/output pb files need to be updated in onnx/models.

**Comment by jcwchen** [comment]
I have merged the PR (https://github.com/onnx/models/pull/534) which updates all input/output to have unique names. @chinhuang007 thank you for catching this and please let me know if you still see issues in the latest test_data_set. Close here now. Feel free to reopen it if you still have questions.
