### ISSUE TITLE
Create a script to verify all models working with provided inputs and outputs

### ISSUE THREAD

**Issue by chinhuang007** [onnx/models#404]
The current models have different completeness in terms of providing proper inputs and outputs for verification against a backend such as ORT. Many have inputs and outputs with all empty string names. Some don't have correct input and output names. I'd like to suggest to add a script to test and verify all existing models using ORT to ensure the provided model, inputs,and outputs have high quality with consistency.

**Comment by wenbingl** [comment]
there are some scripts in https://github.com/onnx/models/tree/master/workflow_scripts to help the check, but it only checked the model after the scripts was merged.

**Comment by jcwchen** [comment]
After #534 merged, now you can use `python workflow_scripts\test_models.py --all_models --target onnxruntime` to test all input/output with ORT by the latest script here: https://github.com/onnx/models/blob/main/workflow_scripts/test_models.py.
