### ISSUE TITLE
Sample test data for RoBERTa are incorrect 

### ISSUE THREAD

**Issue by winnietsang** [onnx/models#408]
RoBERTa-BASE
Base on the [README.md](https://github.com/onnx/models/tree/master/text/machine_comprehension/roberta#input) file for RoBERTa-BASE model there are 1 input and 2 outputs. 
The shape of 'input_ids' is (batch_size, sequence_length) and dtype is int64. 
The shape of 'output_1' is (batch_size, seq_len, 768) and dtype is float32.
The shape of 'output_2' is (batch_size, 768) and dtype s float32. 
However the test data are not in the shape and dtype stated in the README.md file
Inputs/outputs of the model | Expected dtype | Actual dtype in test data | Expected shape | Actual shape in test data                      
----------------------------|-----------------|--------------------------|-----------------|--------------------------
input_ids | int64 | float64 | (batch_size, seq_len) | (1, 9) -> batch_size = 1 and seq_len = 9
output_1 | float32 | float64 | (batch_size, seq_len, 768) | (1, 1, 11, 768) -> batch_size = (1, 1) and seq_len = 11
output_2 | float32 | float64 | (batch_size, 768) | (1,1,768) -> batch_size = (1, 1)

RoBERTa-SequenceClassification
Base on the [README.md](https://github.com/onnx/models/tree/master/text/machine_comprehension/roberta#input) file for RoBERTa-SequenceClassification model there is 1 input and 1 output.
The shape of 'input_ids' is (batch_size, sequence_length) and dtype is int64. 
The shape of 'output' is (batch_size, 2) and dtype is float32.
However the test data are not in the shape and dtype stated in the README.md file
Inputs/outputs of the model | Expected dtype | Actual dtype in test data | Expected shape | Actual shape in test data                      
----------------------------|-----------------|--------------------------|-----------------|--------------------------
input_ids | int64 | float64 | (batch_size, seq_len) | (1, 1, 6) -> batch_size = (1, 1) and seq_len = 6
output | float32 | float64 | (batch_size, 2) | (1, 1, 1, 2) -> batch_size = (1, 1, 1)

Base on the description in [Usage](https://github.com/onnx/models#usage-), the sample test data in the gz file should be ready to use as input and reference output for the model without any manual steps like cast, squeeze, reshape, etc

**Comment by wenbingl** [comment]
is this PR https://github.com/onnx/models/pull/405 fixing the issue your mentioned?

**Comment by winnietsang** [comment]
> is this PR #405 fixing the issue your mentioned?

It fixed the problem in RoBERTa-SequenceClassification but the issue in RoBERTa-BASE is not fix yet.

**Comment by jcwchen** [comment]
IIUC, it should be covered by this PR: https://github.com/onnx/models/pull/473. Close here now. Thanks
