### ISSUE TITLE
 This repository is over its data quota.

### ISSUE THREAD

**Issue by kimjungwow** [onnx/models#447]
# Bug Report

### Which model does this pertain to?
resnet50-v2-7.onnx

### Describe the bug
Can't download the model via git LFS

### Reproduction instructions

Provide a code snippet to reproduce your errors.
```
$ git lfs pull --include="vision/classification/resnet/model/resnet50-v2-7.onnx" --exclude=""
batch response: This repository is over its data quota. Account responsible for L bandwidth should purchase more data packs to restore access.
error: failed to fetch some objects from 'https://github.com/onnx/models.git/infofs'
...
```

### Notes
Related issue : #446

**Comment by prasanthpul** [comment]
increased

**Comment by mikex86** [comment]
It seems like the repository exceeded the LFS data quota again.
Are there any non-git mirrors to prevent this from happening in the future?

![image](https://user-images.githubusercontent.com/41896826/129706072-4e708a4e-4790-4e9f-be74-f91744958fe5.png)
