### ISSUE TITLE
Move the large model files to somewhere else

### ISSUE THREAD

**Issue by houseroad** [onnx/models#47]
GitHub has [100MB disk quota](https://help.github.com/articles/what-is-my-disk-quota/), and our models are usually very large. We should not store them in GitHub directly.

Right now, most of the models are hosted on S3, we should move the rest to somewhere else (e.g., s3, git lfs), too.

**Comment by mx-iao** [comment]
Yes, we've started removing the model files. The last one that needs to be removed is the emotion model and I'll do that today.

**Comment by houseroad** [comment]
@mx-iao Thanks for the update. Ideally the git history should also be cleaned. :-)
