### ISSUE TITLE
MNIST model weights

### ISSUE THREAD

**Issue by ayush1999** [onnx/models#48]
I was loading the MNIST model. I wanted to where the model weights were stored. In other onnx models, the `Graph.initializer` structure holds this information, but in this particular MNIST model, the `Graph.initializer` is empty.

**Comment by ebarsoum** [comment]
Hi @ayush1999  for this model the weights are stored in a Constant OP and not in the initializer.

**Comment by ayush1999** [comment]
@ebarsoum I see. What is the reason behind this difference?

**Comment by ebarsoum** [comment]
Historic, the above model is created from CNTK which uses Constant instead of the initializer. We are in the process of updating CNTK to use initializer instead, and once that work is done I will update MNIST and the emotion model.
