### ISSUE TITLE
Missing output files under test dataset

### ISSUE THREAD

**Issue by wangxudong-cq** [onnx/models#496]
# Bug Report

### Which model does this pertain to?
[https://github.com/onnx/models/blob/master/vision/object_detection_segmentation/ssd-mobilenetv1/model/ssd_mobilenet_v1_10.tar.gz](url)

### Describe the bug
The number of output files under the test dataset does not match the ssd_mobilenet_v1_10.onnx model output
![image](https://user-images.githubusercontent.com/76459010/153140952-f8e237d2-9535-4e95-a566-9667ba64bb8c.png)

### Notes
Pls refer to [https://github.com/onnx/models/blob/master/vision/object_detection_segmentation/ssd-mobilenetv1/model/ssd_mobilenet_v1_12-int8.tar.gz](url)

**Comment by jcwchen** [comment]
Thanks for catching this. After this PR: https://github.com/onnx/models/pull/534, I believe now ssd_mobilenet_v1_10.tar.gz has the right output number. Close here now.
