### ISSUE TITLE
Huggingface Spaces Demos

### ISSUE THREAD

**Issue by AK391** [onnx/models#498]
# Feature Request

Hi, is there any interest in adding demos for the models to Huggingface under a onnx org similar to github?

see examples from Keras and Pytorch
Keras: https://huggingface.co/keras-io
Pytorch: https://huggingface.co/pytorch

The pytorch hub also links back to the demos, for example on the model page here https://pytorch.org/hub/facebookresearch_pytorchvideo_resnet/ with the button "open model demo" opens this demo
https://huggingface.co/spaces/pytorch/3D_ResNet

Similarly, we can help setup a onnx org on huggingface and Gradio Spaces for each model here that can be linked in the readme. Thanks

**Comment by jcwchen** [comment]
HI @AK391,
Thank you for proposing this. May I understand what are the things that need to be done from ONNX? For instance, webpage, demo system, cloud compute behind the demo system (unless the demo system is web-based like ONNXRuntime Web).

For current Keras and PyTorch webpage, are their demo systems running on local web or cloud server?

**Comment by AK391** [comment]
@jcwchen thanks, the only thing needs from the onnx side is to have the links to the spaces in the repo similar to pytorch hub repo here https://github.com/pytorch/hub.

this is what a PR would look like https://github.com/pytorch/hub/pull/274

 I can open PRs once the space is setup on huggingface to add the links to the table in the readme here for example. 

https://github.com/onnx/models#image_classification

 The demos are web based hosted on huggingface spaces, for more info see: https://huggingface.co/docs/hub/spaces

**Comment by jcwchen** [comment]
@AK391 Thank you so much for the detailed explanation! It would also help interested contributors understand how to create a new ONNX demo in huggingface spaces.

**Comment by AK391** [comment]
@jcwchen Great, thanks, I approved your request to join the org https://huggingface.co/onnx, I will start to add the spaces

**Comment by AK391** [comment]
@jcwchen started to add the spaces, opened PR here https://github.com/onnx/models/pull/503
