### ISSUE TITLE
About AlexNet MaxPooling

### ISSUE THREAD

**Issue by tjingrant** [onnx/models#5]
Hi, is it a mistake that the last maxpooling layer of alex net has padding [0, 0, 1, 1]? This node has output named "pool5_1". Changing it to [1, 1, 1, 1] gives correct shape as well as correct results for us.

**Comment by tjingrant** [comment]
I thought all intermediate tensors of alexnet should have their height equal to the width and therefore this padding seems incorrect to me.

**Comment by tjingrant** [comment]
ping @bddppq

**Comment by tjingrant** [comment]
Closing as it seems to be our side of the problem.

**Comment by LucasMahieu** [comment]
Hi,
I have also problems with this network, did you find a solution ? 
If you can take a look at : https://github.com/onnx/models/issues/11
