### ISSUE TITLE
Can't download model file opset_4/resnet50.tar.gz 

### ISSUE THREAD

**Issue by pooyadavoodi** [onnx/models#51]
I am using onnx 1.1.1, where `onnx.defs.onnx_opset_version()` returns 4, and thus Caffe2 tries to download https://s3.amazonaws.com/download.onnx/models/opset_4/resnet50.tar.gz 

Downloading this file gives the following error:

```
$ wget https://s3.amazonaws.com/download.onnx/models/opset_4/resnet50.tar.gz
--2018-05-01 15:11:56--  https://s3.amazonaws.com/download.onnx/models/opset_4/resnet50.tar.gz
Resolving s3.amazonaws.com (s3.amazonaws.com)... 52.216.99.21
Connecting to s3.amazonaws.com (s3.amazonaws.com)|52.216.99.21|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2018-05-01 15:11:56 ERROR 403: Forbidden.
```

**Comment by pooyadavoodi** [comment]
https://s3.amazonaws.com/download.onnx/models/opset_5/resnet50.tar.gz has the same problem, but 3 and 6 work.

**Comment by houseroad** [comment]
@pooyadavoodi we don't provide opset_4 and opset_6 version of resnet50.tar.gz right now in the model zoo.

Acutually, opset_3 should work with onnx 1.1.1.

**Comment by pooyadavoodi** [comment]
Sorry for the delay.
I understand that 3 and 6 work, but the problem is `onnx.defs.onnx_opset_version()` returns 4. If that function returns 3 or 6, then it all made sense.

**Comment by vinitra** [comment]
This should hopefully be addressed with newer versions of resnet50 storing the models in Git LFS!
