### ISSUE TITLE
404 page for ShuffleNet-v2-int8 and vgg16-int8

### ISSUE THREAD

**Issue by georgen117** [onnx/models#512]
# Bug Report
I was attempting to download
- shuffleNet-v2-int8 with sample test data ONNX v1.9
- vgg16-int8 with sample test data ONNX v1.9

the version with the sample test data reached a 404 page.

I was able to download the models without sample testdata.

### Which model does this pertain to?
shuffleNet-v2-int8
vgg16-int8

### Reproduction instructions
Navigate to the model zoo page for the two models and click the download link for the model with test data.

**Comment by jcwchen** [comment]
Hi @georgen117,
Thanks for catching these. I can confirm these two issues:
- shuffleNet-v2-int8.tar.gz might be a typo in this [document](https://github.com/onnx/models/tree/main/vision/classification/shufflenet#model). The correct link should be `https://github.com/onnx/models/blob/main/vision/classification/shufflenet/model/shufflenet-v2-12-int8.tar.gz`
- vgg16-12-int8.tar.gz wasn't included in the original PR: https://github.com/onnx/models/pull/469. @mengniwang95 could you please help us to upload this missing .tar.gz if possible? Thank you for the contribution!

**Comment by mengniwang95** [comment]
hi @georgen117 @jcwchen ,
Sorry for my mistakes, I have fixed these two bugs in https://github.com/onnx/models/pull/513
