### ISSUE TITLE
Does the tiny-yolo-voc.onnx have pads?

### ISSUE THREAD

**Issue by georgeokelly** [onnx/models#53]
When I convert the provided tiny-yolo-voc.onnx to another framework, it goes on well. But when I convert my own tiny-yolo-voc.onnx, it warns me that no supports for pads. Does that mean the provided onnx has no pads? And would you provide with tiny-yolo on COCO? Thanks a lot.

**Comment by snnn** [comment]
We should get this model updated to a new version. This work is on-going.
