### ISSUE TITLE
mnist-12-int8.onnx gives zero output

### ISSUE THREAD

**Issue by Tomiha** [onnx/models#538]
# Ask a Question
Do I need to apply additional preprocessing to the input of the mnist-12-int8.onnx model, compared to the non-quantized versions of the model. I'm currently trying this quantized version of the onnx model with the OnnxRuntime (v1.11.0) and the output seems to be all zeroes..

### Question
I'm currently using the OnnxRuntime (1.11.0) for inference in Unity3D. Inference works perfect with the non-quantized versions of the MNIST model (Same output for non-quantized model version is acquired for both OnnxRuntime and Unity's Barracuda inference engine).

BUT the moment I use the quantized version of the MNIST model (mnist-12-int8) with the exact same input (I assume no additional preprocessing must happen compared to the non-quantized versions) the output seems to be all zeroes. The model loads fine and inference is performed, but the output gives me zeroes. I can't compare against Unity's Barracuda Inference Engine because it doesn't support the required opset - that's why I'm using the OnnxRuntime 1.11.0 directly.

### Further information
mnist-12-int8.onnx
OnnxRuntime 1.11.0
Input >> same as non-quantized versions (like mnist-12 or mnist-8)

Is this issue related to a specific model?  
mnist-12-int8

**Comment by jcwchen** [comment]
@mengniwang95 would you mind to take a look at this question? Thanks!

**Comment by mengniwang95** [comment]
@Tomiha Hi, could you provide any input to reproduce? I run mnist-12 and mnist-12-int8 with the same inputs and their outputs are comparable:
mnist-12: [array([[ -552.70996,   138.26901,  2178.508  ,  2319.8616 , -3466.5378 ,
        -1778.3539 , -6441.8354 ,  8062.959  , -1860.2047 ,  1034.2356 ]],
      dtype=float32)]
mnist-12-int8: [array([[ -539.37665,   119.86147,  2217.4373 ,  2337.2988 , -3475.9827 ,
        -1737.9913 , -6472.5195 ,  8090.6494 , -1917.7836 ,  1078.7533 ]],
      dtype=float32)]
-------------
mnist-12: [array([[  317.01016,  1568.4137 ,  5190.2056 ,  -357.2413 , -2613.7957 ,
        -3612.6416 ,   231.16753, -2029.4198 ,  -259.9232 , -2686.7107 ]],
      dtype=float32)]
mnist-12-int8: [array([[  299.6537 ,  1558.1991 ,  5213.974  ,  -359.5844 , -2696.883  ,
        -3595.8442 ,   179.7922 , -2037.645  ,  -239.72295, -2696.883  ]],
      dtype=float32)]

**Comment by Tomiha** [comment]
Hi @mengniwang95,

Tried it again today (sorry for the delay, had some other stuff to do) and for some reason everything works fine now. Could be that another version of the OnnxRuntime dll was loaded when I was testing before. I'll close the issue. 

Thanks for your time anyway, really appreciated!
