### ISSUE TITLE
Can add mobilenet v1 and v2 onnx files?

### ISSUE THREAD

**Issue by oscarbg** [onnx/models#54]

**Comment by houseroad** [comment]
Yes, we will add it soon.

**Comment by snnn** [comment]
Great!

Could you also add inception_v3 from tensorflow?


https://storage.googleapis.com/download.tensorflow.org/models/inception_v3_2016_08_28_frozen.pb.tar.gz

python -m tf2onnx.convert --input inception_v3_2016_08_28_frozen.pb --inputs input --outputs InceptionV3/Predictions/Reshape_1:0 --output model.onnx

I can also provide the script for generating test data.

**Comment by ankkhedia** [comment]
Hi @oscarbg You can take a look into new ONNX Model Zoo. It has Mobilenet V2 model along with training, inference and validation notebooks.

Feel free to raise a PR if you have something to contribute.
Thanks!

**Comment by oscarbg** [comment]
Hi @ankkhedia,
thanks for pointing out ONNX Model Zoo (https://github.com/onnx/model-zoo) wasn't aware of that project..
closing & will test soon..

**Comment by ankkhedia** [comment]
Hi @oscarbg ONNX Model Zoo (https://github.com/onnx/model-zoo) has been merged with onnx/models. You can take a look here itself.
Thanks!

**Comment by oscarbg** [comment]
Thanks for letting me know!

**Comment by ujsyehao** [comment]
@ankkhedia Hi, Can you add mobilenetv1 and mobilenetv3 onnx?
