### ISSUE TITLE
ResNet models fail to download even with force_reload = True

### ISSUE THREAD

**Issue by diviramon** [onnx/models#541]
# Bug Report

Reset models are not downloading since last merge.

### Which model does this pertain to?

ResNet18/34/50/101/152

### Describe the bug

Trying to load any ResNet model fails with wrong checksum, even after forcing to reload it.

### Reproduction instructions

**System Information**  

OS Platform and Distribution (*e.g. Linux Ubuntu 16.04*):  All
ONNX version (*e.g. 1.6*):  1.11.0
Backend/Runtime version (*e.g. ONNX Runtime 1.1, PyTorch 1.2*):  N/A

Provide a code snippet to reproduce your errors.
```
from onnx import hub as onnx_hub

onnx_hub.load(model="ResNet18", opset=7, force_reload=True)
```

### Notes

Pretty sure last merge caused it since it was working fine on Wednesday.

**Comment by diviramon** [comment]
Hello - Any updates? Thanks

**Comment by jcwchen** [comment]
Hi @diviramon,
Thanks for catching this. It should be related to this: https://github.com/onnx/models/issues/546. I will propose a PR to fix this.

**Comment by jcwchen** [comment]
Also provide a workaround here:
```
from onnx import hub
all_models = hub.list_models(repo="onnx/models:e923e0e19195f7d3ab3ef833d2488e476a6ecbf3")
for model_info in all_models:
    onnx_model = hub.load(model_info.model, repo="onnx/models:e923e0e19195f7d3ab3ef833d2488e476a6ecbf3", force_reload=True, silent=True)

```
If the latest main branch has some broken models or checksum, ONNX Hub can specify an old commit to download. `e923e0e19195f7d3ab3ef833d2488e476a6ecbf3` is the commit ID which updated manifes most recently: https://github.com/onnx/models/pull/478.

**Comment by jcwchen** [comment]
Just merged https://github.com/onnx/models/issues/546. I tried the following command again and now it worked:
```
from onnx import hub as onnx_hub
onnx_hub.load(model="ResNet18", opset=7, force_reload=True)
```
I will close this issue then. Feel free to reopen it if you still see related issues. Thank you for catching it!
