### ISSUE TITLE
tar of models broken?

### ISSUE THREAD

**Issue by Aaronhuang-778** [onnx/models#549]
have the tar.gz file of models all broken? Why the running of test_models.py stops at tarfile.open(file_path, "r:gz")

**Comment by jcwchen** [comment]
Hi @Aaronhuang-778,
How did you run test_models.py? By default it only tests with changed models (from git diff) and you can specify `--all_models` to test all models.

**Comment by Aaronhuang-778** [comment]
> 

Hi~chunwei， I guess it’s due to the path, it is a lit bit diff to install `git lfs` and the `cwd`

**Comment by jcwchen** [comment]
Yes, you should see the complete .tar files after correct git-lfs. At least `test_models.py` works fine in Windows CI and Linux CI. A quick workaround would be you directly downloading all models manually before running the script: `git lfs pull --include="*" --exclude=""`.

**Comment by jcwchen** [comment]
It seems resolved. Feel free to reopen it if you still have any question. Thanks!
