### ISSUE TITLE
Tiny_Yolov2 failed ONNX model checker

### ISSUE THREAD

**Issue by yinghai** [onnx/models#55]
Looks like `tiny_yolov2` only has one input (`image`). For it to be a valid model, all the initializers should be in the input too. @houseroad 

Error log: 
```
E       ValidationError: convolution.W in initializer but not in graph input

../../../../venv/lib/python2.7/site-packages/onnx/checker.py:76: ValidationError
```

**Comment by leodestiny** [comment]
Same error in my computer.

**Comment by prasanthpul** [comment]
This model was converted from CoreML, so we will take a look at the source model and the converter.

**Comment by snnn** [comment]
https://github.com/onnx/onnx/issues/1021

**Comment by vinitra** [comment]
Resolved with https://github.com/onnx/onnx/pull/1718, so I'll close this issue. Feel free to reopen if the error persists.
