### ISSUE TITLE
some model_with_data_path are still missing 

### ISSUE THREAD

**Issue by mszhanyi** [onnx/models#556]
The below models don't have model_with_data_path yet.

https://github.com/onnx/models/blob/e77240a62df68ed13e3138a5812553a552b857bb/ONNX_HUB_MANIFEST.json#L754

https://github.com/onnx/models/blob/e77240a62df68ed13e3138a5812553a552b857bb/ONNX_HUB_MANIFEST.json#L801

https://github.com/onnx/models/blob/e77240a62df68ed13e3138a5812553a552b857bb/ONNX_HUB_MANIFEST.json#L1032

https://github.com/onnx/models/blob/e77240a62df68ed13e3138a5812553a552b857bb/ONNX_HUB_MANIFEST.json#L983

https://github.com/onnx/models/blob/e77240a62df68ed13e3138a5812553a552b857bb/ONNX_HUB_MANIFEST.json#L7286

**Comment by jcwchen** [comment]
Hi @mszhanyi,
Thanks for catching this. I think https://github.com/onnx/models/pull/553 will fix this. Feel free to review it.
