### ISSUE TITLE
emotion_ferplus model has not opset_import field

### ISSUE THREAD

**Issue by leodestiny** [onnx/models#56]
I download emotion_ferplus onnx model https://github.com/onnx/models/tree/master/emotion_ferplus.
But using onnx.checker.check_model function, report: 
<img width="762" alt="image" src="https://user-images.githubusercontent.com/6851716/39788391-e6b6579e-535c-11e8-8981-ab911a1b8211.png">
I found that in emotion_ferplus.onnx, opset_import is [], which is not set.

**Comment by mx-iao** [comment]
Fixed, model now passes the model checker. Thanks!
