### ISSUE TITLE
Update the models

### ISSUE THREAD

**Issue by sushidelivery** [onnx/models#575]
Please update the models for vision/body_analysis/age_gender. The models are failed to be loaded. 

When loading the model, there is an error --> Error message: Protobuf parsing failed

**Comment by jcwchen** [comment]
Hi @sushidelivery,
Similar to https://github.com/onnx/models/issues/569? Did you use git-lfs to download the model?

**Comment by sushidelivery** [comment]
oh i missed it somehow, sorry! it works ;)) 

thanks :)
