### ISSUE TITLE
Can't get accurate prediction on some pre-trained models

### ISSUE THREAD

**Issue by ThomasDelteil** [onnx/models#59]
Hi, 

I get good results on the traditional 1000 imagenet synset using the VGG16, bvlc_googlenet, and VGG19 models, with the data moved to [0, 1] and applied the std and mean normalization from ImageNet.

However I am not able to get accurate predictions using squeezenet, densenet121 pre-trained models using the same pre-processing. Have they been trained on a different synset? Do they need a specific pre-processing?

I am using MXNet as the backend.

**Comment by ankkhedia** [comment]
Hi @ThomasDelteil , This is the new model zoo https://github.com/onnx/model-zoo. Pleas feel free to checkout the models. The models come along with the synset and preprocessing code. 

Thanks!
