### ISSUE TITLE
Update to .onnx file extension and flat folder structure

### ISSUE THREAD

**Issue by lutzroeder** [onnx/models#6]
Should the models get updated to use the `.onnx` file extension?

Also wondering, should the `.tar.gz` files be linked directly from the top-level `README.md` and the files named `bvlc_alexnet.onnx`, `inception_v2.onnx` etc instead of `model.db`?

**Comment by prasanthpul** [comment]
Using .onnx makes sense to me.
I believe the files are named model and put in different subfolders to simplify automated testing.
@bddppq to comment too

**Comment by dzhulgakov** [comment]
I have slight preference for .onnx too (as it's easier to distinguish which format the .pb is in). Shall we go for it?

**Comment by bddppq** [comment]
Two reasons for why I'm a little bit hesitated to change the file extension:

1. It confuses users. With the .pb suffix users immediately know the models files are in fact protobuf files, all pb libs/tools are automatically usable.
2. This second reason does not only apply to changing the suffix but in general to changing the model file name. We hardcoded this in couple places, including the ONNX backend test suite. If we change model files' name now (and presumably also update all the places in repos we have control), all installations of older versions of onnx (including the v1.0) and external repos that depend on onnx will encounter problem.

**Comment by prasanthpul** [comment]
My thoughts:
1) I feel it's more important for user to know it is a ONNX file and thus can be used by various ONNX-compatible tools/libraries than to know it is protobuf. The only hesitation I can see is if we think we will move to a multi-file format soon and .onnx will be used for the container, i.e. zip file.
2) This is a valid concern but we should implement versioning on the models. Old versions should be left as-is. A new version should be created with the updates.

**Comment by lutzroeder** [comment]
Agree, `.onnx` is the way to go. 

For example, an app like Netron supports loading ONNX and TensorFlow models and both use `.pb`. There is no way telling which format a file contains other than crossing fingers that the `decode()` will crash gracefully. Also, the app registers both file extension with the shell and all ONNX `.pb` files now show as `TensorFlow Model` in Explorer or Finder. Not a great experience...

`.pb` files require a known `.proto` to be loaded and experts that can figure out those steps probably won't stumble on how to handle an `.onnx` file. CoreML seems to be similar in that regard and has opted for protobuf with an `.mlmodel` extension.

**Comment by gramalingam** [comment]
I agree, .onnx is better than .pb

**Comment by bddppq** [comment]
Alright majority rules :-) Updated the corresponding issue #14

**Comment by houseroad** [comment]
Fixed here: https://github.com/onnx/onnx/pull/541
