### ISSUE TITLE
Error in the tiny yolo v2 model

### ISSUE THREAD

**Issue by ayush1999** [onnx/models#60]
I was trying out the tiny yolo v2 model, when I came across a strange error. Apparently, there exist a `convolution.W` key, which is called without being initialized. Can someone tell me the reason behind this?

**Comment by ayush1999** [comment]
@bddppq Any idea?

**Comment by snnn** [comment]
@linkerzhang Could you please re-generate the model and let @ayush1999 test again?

**Comment by vinitra** [comment]
#55 seems to address the same issue regarding initializers. It was resolved in the following two discussions:
https://github.com/onnx/onnx/pull/1718
https://github.com/onnx/onnx/issues/1021
