### ISSUE TITLE
What is the current total model zoo size

### ISSUE THREAD

**Issue by cjvolzka** [onnx/models#638]
# Ask a Question

What is the current approximate size of the onnx model zoo following https://github.com/onnx/models/pull/636?

### Question
Previously, we kept a local cache of the model zoo for regression testing. I'd like an estimate for the total size so we can decide if we want to continue that or not. I'm not sure of a way to have `git lfs` report total size short of actually downloading the entire zoo. However I ran out of local space attempting that.

### Further information
NA

Is this issue related to a specific model?  
No

### Notes
NA

**Comment by ramkrishna2910** [comment]
Hi @cjvolzka 
The size of the model zoo now is close to a terabyte and this will continue to grow.

**Comment by cjvolzka** [comment]
@ramkrishna2910, thanks for the fast response! I ran out of space at 750GB trying to download it last night so I wasn't too far away then (until it grows more). I was guessing 1-2TB so I was in the ballpark.

Thanks
