### ISSUE TITLE
Will the archive be completely deleted by February?

### ISSUE THREAD

**Issue by claudiotancredi** [onnx/models#639]
# Ask a Question

### Question
Hi, I'm currently working on a university project that uses several models from the [archive](https://github.com/onnx/models/tree/main/archive). Will the archive be deleted by February (project deadline)?

### Further information
Ideally, after the project deadline the archive should still be available so that our professor could check that we've indeed worked on your .onnx files. This is the reason why I'm asking when it will be dismissed.

**Comment by ramkrishna2910** [comment]
Hi @claudiotancredi 
Thanks for the issue.
We have received enough signal that the legacy models in the zoo are being actively used. We will continue to maintain them under archive but we also recommend using the newer models as they are exported with the latest opsets.

**Comment by claudiotancredi** [comment]
Understood, thank you for your time. 
I'll close the issue.
