### ISSUE TITLE
ResNet50 Labels Giving Wrong Results

### ISSUE THREAD

**Issue by sgarcia22** [onnx/models#64]
Hi everyone, I have successfully imported the ONNX model for ResNet50, I tried both the master and release versions, and labels from here: http://image-net.org/challenges/LSVRC/2015/browse-synsets (copied & pasted, and parsed in Python), and I tried the IMAGENET 2012 list as well http://www.image-net.org/archive/words.txt. 

If I put a golden retriever it gives me .999.. percent accuracy... of a rugby ball. Does anyone know where the correct dataset is? The evaluated output does not correspond to the correct label. Thanks.

**Comment by XiaoGeMa** [comment]
The same

**Comment by houseroad** [comment]
@sgarcia22 could you try to use the mean to preprocess your input? https://github.com/Azure/BatchAI/blob/master/recipes/Caffe2/Caffe2-GPU-Distributed/resnet50_trainer.py#L61

**Comment by sgarcia22** [comment]
Yes I had to resize/center crop to 224x224 then process the mean & std. Thanks for the help!

**Comment by 8greg8** [comment]
@sgarcia22 can you please tell me how did you process the mean and std? 

I'm using      [https://github.com/BVLC/caffe/blob/master/python/caffe/imagenet/ilsvrc_2012_mean.npy](url) but this doesn't seem to work. 

Also which code to label mapping did you use?
