### ISSUE TITLE
Most of the links in the README.md file are broken

### ISSUE THREAD

**Issue by venkatvellaichamy** [onnx/models#641]
# Bug Report

### Describe the bug
Links in the README.md file are broken. Links to the following text in the README.md file

- ONNX Model Zoo website
- TurnkeyML toolchain
- Model Zoo webpage
- contribution guidelines

### Reproduction instructions

1. Navigate to the github page: https://github.com/onnx/models
2. You should now see the README section
3. Try clicking the links to the following words
- ONNX Model Zoo website
- TurnkeyML toolchain
- Model Zoo webpage
- contribution guidelines
4. Notice that the links are broken

**Comment by Maxim-Doronin** [comment]
Seems to be fixed https://github.com/onnx/models/commit/b64863627bd36909b2f628885f6871fb8b1a300e

**Comment by ramkrishna2910** [comment]
Closed with #642
