### ISSUE TITLE
Resnet50 is no longer 'available' through the hub.load() since the model hub revamp

### ISSUE THREAD

**Issue by rchevalier-brainchip** [onnx/models#646]
### Discussed in https://github.com/onnx/models/discussions/645

<div type='discussions-op-text'>

<sup>Originally posted by **rchevalier-brainchip** December 26, 2023</sup>
Hi,

Currently, with onnx 1.15.0, using `hub.load('resnet50')` fails with `HTTP Error 404`.
Hub tries to get the model from https://media.githubusercontent.com/media/onnx/models/main/archive/vision/classification/resnet/model/resnet50-v1-7.onnx as per the manifest info.
 
On the contrary: 
`hub.load("resnet50", repo="onnx/models:5faef4c33eba0395177850e1e31c4a6a9e634c82")` works fine (i.e. using the commit pre-revamp) and fetches the model from https://media.githubusercontent.com/media/onnx/models/5faef4c33eba0395177850e1e31c4a6a9e634c82/vision/classification/resnet/model/resnet50-v1-7.onnx

What is the correct way to go?

Thanks!
RC</div>

**Comment by ramkrishna2910** [comment]
Hi @rchevalier-brainchip 
Thanks for bringing this to our attention. This issue is caused due to a folder renaming in the repo.
#647 is pending review right now and once merged will fix the above issue.

@jcwchen

**Comment by rchevalier-brainchip** [comment]
Thanks a lot!

**Comment by ramkrishna2910** [comment]
#647 has merged and I can verify the following:
```
from onnx import hub
hub.load("resnet50")
```

Please close the issue if there are no further questions :)

**Comment by rchevalier-brainchip** [comment]
Thanks for the quick fix :) all good on my side !
