### ISSUE TITLE
Question about the shape of bvlc_alexnet model input 'data_0'

### ISSUE THREAD

**Issue by huningxin** [onnx/models#7]
The shape of input `data_0` of [onnx bvlc_alexnet model](https://github.com/onnx/models/tree/master/bvlc_alexnet) is `[1, 3, 224, 224]`. 

According to http://cs231n.github.io/convolutional-networks/, this causes the Conv node's output `conv1_1` shape to be non-integer. 

I'd like to understand why `data_0` is not `[1, 3, 227, 227]` which is used in other models, like [caffe2 bvlc_alexnet model](https://github.com/BVLC/caffe/blob/master/models/bvlc_alexnet/deploy.prototxt).

Thanks!

**Comment by houseroad** [comment]
Right now, most of the existing models take `[1, 3, 224, 224]` as inputs. The models are not sensitive to the input size.
