### ISSUE TITLE
potential issue with tinyyolov2 output

### ISSUE THREAD

**Issue by prasanthpul** [onnx/models#73]
See the issue here which was closed since this issue is now open: https://github.com/onnx/onnx/issues/1162

**Comment by fldvrees** [comment]
If anyone has problems with parsing the output of the tiny YOLOv2 model.
elbruno has an[ excellent example](https://github.com/elbruno/Blog/tree/master/20180709%20UwpMLNet%20TinyYoloV3) of how the output should be parsed.

As far as I'm concerned there is nothing wrong with the tiny YOLOv2 ONNX model, and this issue may be closed

**Comment by mx-iao** [comment]
@aoke79 please see the above example for guidance on processing the model output. Closing this issue now; please reopen if you need to.
