### ISSUE TITLE
ImageScaler in tiny_yolov2 model

### ISSUE THREAD

**Issue by issuehsu** [onnx/models#76]
ImageScaler operation is not supported in Caffe2.
Since the ONNX models usage states that "Every ONNX backend should support running these models out of the box", is this model satisfy the portability of ONNX models?

I also wonder whether models from CNTK (emotion_ferplus, mnist) and CoreML (tiny_yolov2) satisfy the portability.

**Comment by prasanthpul** [comment]
Models that use core ops should be portable. If a model uses core ops and doesn't work with some tool, then likely the tool is not meeting the spec. The model zoo documentation is being updated and this verbiage should be changed/clarified. @abhinavs95 can you make sure this is clear in the new readme?

That said, in this case ImageScaler is an experimental ops defined in the spec (https://github.com/onnx/onnx/blob/master/docs/Operators.md#ImageScaler). Experimental ops are not required to be implemented by everyone.

Models that use experimental ops should explicitly call this out in the readme. @mx-iao can you update readme files? 
The model checker should indicate whether a model uses only core ops, experimental ops, or custom ops. @linkerzhang can we do this as we enhance the checker?

@Issue-Hsu did you run into any specific problem with emotion_ferplus and mnist?

**Comment by houseroad** [comment]
@snnn We are working on an ONNX backend scoreboard. Hopefully it will be available in one or two months.

**Comment by Issue-Hsu** [comment]
@prasanthpul Yes, we try using Caffe2 to run tiny_yolov2 (opset_7) and see following error message:
terminate called after throwing an instance of 'caffe2::EnforceNotMet'
  what():  [enforce fail at backend.cc:1004] . Don't know how to translate op ImageScaler

**Comment by EvrenGursoy** [comment]
I'm intending to have a go at creating the ImageScaler op at the Caffe2 end. To do this and be able to the import the tiny-yolo onnx model to Caffe2, is the only thing that I need to do to create a suitable custom operator at the Caffe2 side? Or do I also need to do something with caffe2-onnx bundled with PyTorch / Caffe2?

**Comment by houseroad** [comment]
@EvrenGursoy if the operator definition in both onnx and caffe2 matches perfectly, you don't need to extra binding.

**Comment by snnn** [comment]
Hi all,

ImageScaler is still an experimental op. if a model contains an experimental op, it means this model may not be supported in a newer ONNX version.  Here I'm saying ONNX version, not opset. 

AFAIK, no tools or onnx backend can support multiple ONNX versions at the same time. It can support multiple opsets ,not onnx versions. If somebody downloaded the tiny_yolov2 model from here, today, and saved it to his disk. Then if one month later, someone deleted the ImageScaler OP from the latest ONNX release. Then it would very hard for this user, to figure this model file can work with which ONNX version. As there is NO onnx version in the model file. Looking up onnx git history? Too bad! Also,  he would be very hard to find a backend to load and run this model.  Absolutely this is not what we want.

**Comment by owulveryck** [comment]
Hello,

Do you know where I can find a reference implementation of the `ImageScaler` operator? I need to implement it into [Gorgonia](https://github.com/gorgonia/gorgonia) to use the model with [ONNX-Go](https://github.com/owulveryck/onnx-go).

**Comment by prasanthpul** [comment]
https://github.com/Microsoft/onnxruntime/ implements it.

**Comment by ebarsoum** [comment]
Here the implementation: https://github.com/Microsoft/onnxruntime/blob/master/onnxruntime/core/providers/cpu/tensor/image_scaler.h

**Comment by owulveryck** [comment]
I think I may have been too slow to implement it;
it looks like the ImageScaler op has disappeared from the experimental operator list and from the onnxruntime implementation.
The problem is now that the tiny yolo v2 in the model zoo is using an unknown operator.

**Comment by prasanthpul** [comment]
Thanks for bringing this up. ImageScaler was experimental and has since been removed (it can be decomposed as Mul+Add). ONNX Runtime still supports ImageScaler op due to backwards compatibility requirements, however we do need to update the model zoo model to not use it. @EmmaNingMS

**Comment by linkerzhang** [comment]
yes, ONNXRUNTIME still supports the ImageScaler till opset 10 for backward compatibility.

**Comment by jiafatom** [comment]
@issuehsu I just updated the tiny yolov2 models in model zoo, the new model does not have ImageScaler anymore, please check the models for opset 7 and 8.
