### ISSUE TITLE
ShuffleNet Reshape Problems

### ISSUE THREAD

**Issue by nickfeeney** [onnx/models#77]
Hey, I have been looking at the shufflenet model and have noticed some issues. First and most serious is the over use of reshape nodes. 

If Reshapes from a 4D tensor to a 5D Tensor then Transposes then Reshapes back to 4D. This is unnecessary it can simply Transpose in 4D space. This eliminates the reshape nodes entirely.

The second issue is that the data inside the reshape "Shape" tensor is strange. It should be a simple 1D array of 4 or 5 elements but instead its a list of lists of ints looking like this 
type: int64[5]
[
    {
        "_buffer": {
            "0": 1,
            "1": 0,
            "2": 0,
            "3": 0,
            "4": 0,
            "5": 0,
            "6": 0,
            "7": 0
        }
    },
    {
        "_buffer": {}
    },
    {
        "_buffer": {}
    },
    {
        "_buffer": {}
    },
    {
        "_buffer": {}
    }
]

I purpose that the model be updated without reshape nodes and the transpose be updated to have perms equal to 1,0,2,3(currently 0,2,1,3,4)

**Comment by prasanthpul** [comment]
@houseroad can you comment on why the model does this currently? Seems like we can optimize as @nickfeeney suggests

**Comment by houseroad** [comment]
There is a new operator called `ChannelShuffle` introduced in ShuffleNet. Caffe2 supports it, however, there is no corresponding operator in ONNX. The right way to translate it is 1) reshape a [N, C, H, W] tensor to a [N, G, C', H, W] tensor, 2) transpose the G and C', 3) Reshape it back to [N, C, H, W]. This is the story behind such operator sequences. 

More details can be found here: https://github.com/MG2033/ShuffleNet

**Comment by nickfeeney** [comment]
@houseroad Ok that sounds non trivial and my proposal wouldn't do that. But I think that the reshape->transpose->reshape still doesn't accomplish that. It transposes [1, C, H, W]-> [1,1,C,H,W]->[1, C, 1, H, W]->[C, 1, H, W]. The reshape data needs to be formed correctly to split C into G and C'

**Comment by nickfeeney** [comment]
@houseroad Also I think that what you need to be doing is splitting C into [C', G](not [G, C']) then transpose it to [G, C']. That would make it map to the NCHW format of convolution in Onnx which expects channels to be grouped next to each other for convolution with Group count(kind of like [N,G,C',H,W])

**Comment by nickfeeney** [comment]
@houseroad Sorry I am wrong about the order. it needs to come out of the 1x1 Conv as [NCHW] then reshaped into a [N, 4, 28, H, W] transposed into [N, 28, 4, H, W] reshaped into [N,112, H, W], where G = 4 and c' = 28. This is not what it is doing today.

**Comment by houseroad** [comment]
I have manually checked the data, netron didn't correctly show the data. For example, the data is 1, 4, 136, 7, 7, it shows like the following:
`
type: int64[5]
[
{
"_buffer": {
"0": 1,
"1": 0,
"2": 0,
"3": 0,
"4": 0,
"5": 0,
"6": 0,
"7": 0
}
},
{
"_buffer": {}
},
{
"_buffer": {}
},
{
"_buffer": {}
},
{
"_buffer": {}
}
]
`
So the model itself is correct. And no performance issue, too. Feel free to close it.

**Comment by lutzroeder** [comment]
See lutzroeder/Netron#128
