### ISSUE TITLE
Can't run onnx backend for test data

### ISSUE THREAD

**Issue by suryaprakaz** [onnx/models#78]
I'm trying to run the onnx backend interpreter on a test input data for the resnet50 model

Code is the same as what's provided in the [README](https://github.com/onnx/models/blob/master/README.md) file
```
Traceback (most recent call last):
  File "onnx_checker.py", line 34, in <module>
    outputs = list(backend.Backend.run_model(model, inputs))
  File "/usr/local/lib/python2.7/dist-packages/onnx/backend/base.py", line 76, in run_model
    assert backend is not None
AssertionError
```

**Comment by ankkhedia** [comment]
Hi @suryaprakaz Which model did you use ? Could you point me to exact one?

**Comment by abhinavs95** [comment]
@suryaprakaz the code provided in the readme is used by the platforms supporting ONNX in their CI and cannot be used as is.

@houseroad @mx-iao @prasanthpul Should we move this code elsewhere or provide clarifications on how to use it?

**Comment by houseroad** [comment]
@abhinavs95 this is the recommend way to support ONNX, please check https://github.com/onnx/onnx/blob/master/docs/ImplementingAnOnnxBackend.md

**Comment by houseroad** [comment]
@suryaprakaz ONNX itself does not support any real backend. Please use the frameworks which provide onnx support, such as Caffe2 (merged with pytorch), CNTK, MxNet, etc.

**Comment by mx-iao** [comment]
@suryaprakaz as houseroad mentioned, please use a framework that supports ONNX to evaluate the test data, or the [ONNX Runtime](https://pypi.org/project/onnxruntime/). I have opened up a PR (#107) to add clarification in the readme. Closing the issue now; please reopen if you have additional issues.
