### ISSUE TITLE
Unsqueeze in recent inception_v2

### ISSUE THREAD

**Issue by lutzroeder** [onnx/models#79]
Recent versions of `inception_v2` include a lot of `Unsqueeze` operations. Are these necessary or a bug in the converter?

![model](https://user-images.githubusercontent.com/438516/42739268-2d4b97de-8849-11e8-85a5-2cafd7ad7c78.png)

**Comment by Issue-Hsu** [comment]
It seems Unsqueeze op is to handle broadcast attribute in element-wise op

**Comment by riacheruvu** [comment]
Netron shows that the Unsqueeze node in Inception_v2 takes as input a large array (as shown in the attached picture), which is **not** in the onnx file or fed as input to the Unsqueeze node. Where is the data in the Unsqueeze node coming from? 
![screenshot](https://user-images.githubusercontent.com/22090501/45063141-5b9afb80-b061-11e8-976e-8fd366ad6044.png)

Thank you for the help!
