### ISSUE TITLE
Bad shapes of npz test data in Emotion FER+

### ISSUE THREAD

**Issue by tsocha** [onnx/models#81]
While I've been checking ONNX models I realized that Emotion FER+ test data shapes differ from other models.
In all examples data in NPZ files are wrapped up in one more extra dimension, but data for FER+ are not.
Therefore official ONNX test suite doesn't handle it properly and I get an error that output shape `(1, 8)` doesn't match expected `(8,)` while `(1, 8)` is a valid output shape.

Please update test data for FER+ model, so they are coherent with other models

**Emotion FER+**:
_Emotion FER+ opset7 **pb** test case:_
Input:
test_data_set_0/input_0.pb shape:   `(1, 1, 64, 64)`
Output:
test_data_set_0/input_0.pb shape:   `(1, 8)`

_Emotion FER+ opset7 **npz** test case:_
Input:
test_data_0.npz shape: `(1, 1, 64, 64)` <= **not** wrapped up in one more extra dimension
Output:
test_data_0.npz shape: `(1, 8)`  <= **not** wrapped up in one more extra dimension

**Densenet121:**
_Densenet121 opset7 **pb** test case:_
Input:
test_data_set_0/input_0.pb:   `(1, 3, 224, 224)`
Output:
test_data_set_0/input_0.pb:   `(1, 1000, 1, 1)`

_Densenet121 opset7 **npz** test case:_
Input:
test_data_0.npz input shape: `(1, 1, 3, 224, 224)` <= wrapped up in one more extra dimension
Output:
test_data_0.npz output shape: `(1, 1, 1000, 1, 1)`   <= wrapped up in one more extra dimension

**Comment by tsocha** [comment]
@mx-iao could you take a look at this, please.

**Comment by mx-iao** [comment]
@houseroad is there any reason why the .npz data has an one more dimension than the .pb data? Can we keep it consistent across the .npz and .pb data to reduce confusion?

**Comment by houseroad** [comment]
Because all the inputs (a list of tensors) are serialized into one `.npz`. But `.pb` only contain one tensor. I would suggest to keep .pb to reduce the confusion.

**Comment by mx-iao** [comment]
@tsocha I'll go through the emotion, mnist, & tiny-yolo models and make sure the file names are consistent. I'll also add a note to to the pull request template about the expected naming conventions for the sample data.
@houseroad Should I just remove the .npz data then? I recall we had in a spec somewhere that going forward we would just provide .pb data anyways.

**Comment by houseroad** [comment]
@mx-iao as long as you provide the enough test data in pb format, removing .npz is fine.

**Comment by mx-iao** [comment]
@tsocha I've updated all the test data files for mnist, emotion, & tiny yolo to be consistent. Let me know if you find any issues.
