### ISSUE TITLE
Incorrect MNIST models.

### ISSUE THREAD

**Issue by arogowie-intel** [onnx/models#85]
Hi, 

I'd like to report incorrect MNIST models, both opset version 1 and 7. 

Model with opset version 1 fails ONNX checker (#66) with `opset_import` attribute not set, whereas opset version 7 has both `pads`  and `auto_pad` attributes set - discussion [here](https://github.com/onnx/onnx/issues/1230).

Please update models.

**Comment by snnn** [comment]
I think the model is correct, the document is wrong. NOTSET is the default value of this attribute, so it must be valid.

**Comment by postrational** [comment]
It seems `NOTSET` is mentioned in the ONNX definitions here:
https://github.com/onnx/onnx/blob/4695828eac9b31c97fc211b43609c4ba3a9cd9e7/onnx/defs/nn/defs.cc#L205

The default value is not presented on the generated `Operators.md` documentation:
https://github.com/onnx/onnx/blob/master/docs/Operators.md

**Comment by houseroad** [comment]
The document is updated. So close the issue
