### ISSUE TITLE
resnet 50 preprocessing steps are unclear

### ISSUE THREAD

**Issue by martinb35** [onnx/models#89]
I see the notes on mean, std, and scale, but I'm not sure what to do with those. Can you provide a code sample?

**Comment by ankkhedia** [comment]
@martinb35 you can check out the details here- https://github.com/onnx/models/tree/master/models/image_classification/resnet#preprocessing

For preprocessing code sample, please check out https://github.com/onnx/models/blob/master/models/image_classification/imagenet_preprocess.py

**Comment by prasanthpul** [comment]
https://github.com/onnx/models/tree/master/models/image_classification/resnet also shows numpy-based python code for preprocessing.
