### ISSUE TITLE
Source of input data to Unsqueeze in Inception_v2 and DenseNet121 Opset 8 unclear

### ISSUE THREAD

**Issue by riacheruvu** [onnx/models#92]
Netron shows that the Unsqueeze node in Inception_v2 takes as input a large array (as shown in the attached picture), which is not in the onnx file or fed as input to the Unsqueeze node. This is also occurring in DenseNet121. Where is the data in the Unsqueeze node coming from or is this a bug? 

If this is not the right place to post this, please let me know.

![screenshot](https://user-images.githubusercontent.com/22090501/45115672-66a76780-b105-11e8-9d31-0c8acc67ecb8.png)

**Comment by lutzroeder** [comment]
The data is from a preinitialized tensor in `model.graph.initializer`. The tensor name is `conv1/7x7_s2/bn/sc_w_0`.

**Comment by riacheruvu** [comment]
Thank you!
