### ISSUE TITLE
Duplicate VGG19 models

### ISSUE THREAD

**Issue by lutzroeder** [onnx/models#93]
There are two different `VGG19` models in the model zoo. Can the files be consolidated or renamed so users referring  to "VGG19 in the model zoo" will be less ambiguous.

https://github.com/onnx/models/tree/master/vgg19
https://github.com/onnx/models/tree/master/models/image_classification/vgg

**Comment by snnn** [comment]
"The VGG19 in the model zoo generated from caffe2"
"The VGG19 in the model zoo generated from mxnet"

That would be enough.

**Comment by houseroad** [comment]
@snnn thanks for the explanation

**Comment by prasanthpul** [comment]
That's pretty confusing for the users of the zoo to have 2 different versions of the model. Which one should they use and why?

**Comment by houseroad** [comment]
probably we can have some evaluation. And only keep one.

**Comment by prasanthpul** [comment]
we don't even link to both from the TOC so one of the models is "hidden".

**Comment by crahrig** [comment]
Adding on here that this is also captured by #82

**Comment by snnn** [comment]
Hi @ankkhedia ,

Is there any update on this bug: https://github.com/onnx/models/issues/91 ?  Does it only affect the resnet100 model? 

Thanks.

**Comment by ankkhedia** [comment]
@snnn got a little busy and was not able to look into the issue #91, I will try to address the issue by next week. Sorry for the inconvenience.

**Comment by snnn** [comment]
Thank you @ankkhedia

**Comment by mx-iao** [comment]
@snnn @ankkhedia @prasanthpul @houseroad have we reached consensus on this? either 1) merge and keep only one model or 2) keep both, group in same folder, and differentiate based on training framework used ?

**Comment by vandanavk** [comment]
> The VGG19 model from mxnet seems having some problems. The input of a GEMM op is not a 2-D tensor.

This should be fixed with PR apache/incubator-mxnet#13356.

**Comment by snnn** [comment]
> > The VGG19 model from mxnet seems having some problems. The input of a GEMM op is not a 2-D tensor.
> 
> This should be fixed with PR [apache/incubator-mxnet#13356](https://github.com/apache/incubator-mxnet/pull/13356).

So, someone will update the models here?

**Comment by ankkhedia** [comment]
@snnn I will update the models after generating them with this fix.

**Comment by lutzroeder** [comment]
The actual issue seems to be there are duplicate VGG19 models in the zoo (see above). How does "updating" the files resolve this issue? Shouldn't one set be removed or the `README.md` files be updated to clarify?

**Comment by ankkhedia** [comment]
@lutzroeder This is about @snnn comment about issues with MXNet generated models.
Regarding duplicate models, the models have been generated from different frameworks and there is no clear consensus as to remove the models or keep both in same folder and differentiate on basis of names

**Comment by ankkhedia** [comment]
@snnn The models has been uploaded after the fix.
